import * as path from 'node:path';
import { parseAriaCandidates, textSimilarity } from '@piwitests/core/locator-fingerprint';
import { LOCATOR_BUILDER_METHODS } from '@piwitests/core/locator-methods';

/**
 * Reporter-local locator healing.
 *
 * The pure surface — alternative generation, stability scoring, ARIA-role
 * resolution, the role maps and the captured-attribute whitelist — lives in
 * `@piwitests/core` (bundled into `dist/` at build time, so nothing
 * monorepo-relative leaks into the published package). It is re-exported from
 * here so existing importers (`capture-fixtures.ts`, `pick-on-failure.ts`, the
 * unit tests) keep importing it from this module.
 *
 * This module keeps only the reporter-only runtime: call-site capture (needs the
 * Node stack), snapshot dedupe, the fixture-proxy method surface, and the
 * failure-time locator suggestion + rendering.
 */

// ── Shared pure surface (single source of truth in @piwitests/core) ──────────
export {
  CAPTURED_ATTRIBUTES,
  INPUT_TYPE_TO_ROLE,
  TAG_TO_ROLE,
  approximateAccessibleName,
  classifyCssStability,
  generateAlternatives,
  headingLevel,
  isAutoGenerated,
  resolveAriaRole,
} from '@piwitests/core/locator-generation';
export type {
  AncestorAnchor,
  ElementAttributes,
  LocatorSnapshot,
  RankedLocator,
  RolePosition,
  SelectorCounts,
} from '@piwitests/core/locator-healing-types';

import type { LocatorSnapshot } from '@piwitests/core/locator-healing-types';

/**
 * Drop repeated captures of the same call site before attaching: a loop (or a
 * page-object method called repeatedly) produces one snapshot per action, but
 * the server keeps only the latest per location anyway. Keeps the last
 * element-bearing snapshot per location — falling back to the last placeholder
 * when no capture resolved, so the location still counts as "seen this run"
 * for the server's stale-location purge. Entries with no location pass through.
 */
export function dedupeSnapshotsByLocation(snaps: LocatorSnapshot[]): LocatorSnapshot[] {
  const lastWithElement = new Map<string, number>();
  const lastAny = new Map<string, number>();
  snaps.forEach((s, i) => {
    if (!s.location) return;
    lastAny.set(s.location, i);
    if (s.element) lastWithElement.set(s.location, i);
  });
  return snaps.filter((s, i) => {
    if (!s.location) return true;
    return (lastWithElement.get(s.location) ?? lastAny.get(s.location)) === i;
  });
}

// ── Playwright method surface (shared with the fixture proxy) ────────────────

/**
 * Page-level locator-building methods wrapped by the capture proxy. Imported by
 * both the capture fixtures (`capture-fixtures.ts`) and the dogfooding
 * `application/tests/fixtures.ts` so the two stay in sync (a prior drift missed
 * `scrollIntoViewIfNeeded`).
 */
export const LOCATOR_METHODS: string[] = [...LOCATOR_BUILDER_METHODS];

/**
 * Methods that can be chained onto a wrapped locator. Locator-creating chains
 * (those also in `LOCATOR_METHODS`) update the origin; positional/filter chains
 * (`first`, `nth`, `filter`, …) narrow without changing locator identity.
 */
export const CHAIN_METHODS: string[] = [
  'first',
  'nth',
  'last',
  'filter',
  'and',
  'or',
  'locator',
  'getByRole',
  'getByTestId',
  'getByText',
  'getByLabel',
  'getByPlaceholder',
  'getByAltText',
  'getByTitle',
];

/** Locator action methods that trigger element capture. */
export const ACTION_METHODS: string[] = [
  'click',
  'fill',
  'check',
  'uncheck',
  'selectOption',
  'dblclick',
  'tap',
  'hover',
  'press',
  'type',
  'pressSequentially',
  'clear',
  'setInputFiles',
  'dragTo',
  'focus',
  'blur',
  'scrollIntoViewIfNeeded',
  'dispatchEvent',
  'selectText',
  // Not an action, but a successful waitFor proves the element resolved — the
  // closest capture hook available for assertion-style usage of a locator.
  'waitFor',
];

/** Chain methods that create a new locator scope (origin tracks the chain call). */
export const LOCATOR_CREATING_CHAINS: ReadonlySet<string> = new Set(LOCATOR_METHODS);

// ── Accessible name extraction ───────────────────────────────────────────────

/**
 * Extract the accessible name from a YAML-like ariaSnapshot() output.
 *
 * Format example:
 *   - button "Submit order"
 *   - heading "Welcome, Alice"
 *   - textbox "Email" [ref=e12]
 *   - generic
 *
 * Returns the first quoted string after the role, or null if none found.
 */
export function extractAccessibleName(ariaSnapshot: string | null): string | null {
  if (!ariaSnapshot) return null;

  // Match the role line:  - role "name" [...]
  // The name is the first double-quoted string after the role keyword.
  const match = ariaSnapshot.match(/- \w+ "([^"]+)"/);
  if (match) return match[1];

  return null;
}

// ── Runtime locator suggestion (the "element changed" case) ──────────────────

/** A failed locator action, used to suggest a fresh locator from the live page. */
export interface FailedLocatorInfo {
  method: string;
  args: unknown[];
  /** Test call site (`file:line:col`) of the failed action, when captured. */
  location?: string | null;
}

export interface LocatorSuggestion {
  /** The failed locator rendered as source, e.g. `getByText('Go to page')`. */
  failing: string;
  /** Fresh locator suggestions for the element's current identity, best first. */
  suggestions: string[];
}

/** Name-based locator methods — the only ones whose target can be re-found by accessible name. */
const NAME_BASED_METHODS = new Set([
  'getByText',
  'getByRole',
  'getByLabel',
  'getByPlaceholder',
  'getByTitle',
  'getByAltText',
]);

const escAttr = (s: string): string => s.replaceAll('\\', '\\\\').replaceAll("'", "\\'");

const SUGG_TEXT_ROLES = new Set([
  'button',
  'link',
  'heading',
  'menuitem',
  'tab',
  'option',
  'cell',
  'columnheader',
  'rowheader',
  'gridcell',
  'treeitem',
  'listitem',
  'checkbox',
  'radio',
  'switch',
]);
const SUGG_FIELD_ROLES = new Set(['textbox', 'combobox', 'searchbox', 'spinbutton', 'slider']);

/** Extract the role (for getByRole), targeted accessible name, and heading level from a failed locator's args. */
function failedNameAndRole(failed: FailedLocatorInfo): {
  role: string | null;
  name: string | null;
  level: number | null;
} {
  if (failed.method === 'getByRole') {
    const role = typeof failed.args[0] === 'string' ? (failed.args[0] as string) : null;
    const opts = failed.args[1] as Record<string, unknown> | undefined;
    const name = opts && typeof opts.name === 'string' ? (opts.name as string) : null;
    const level = opts && typeof opts.level === 'number' ? (opts.level as number) : null;
    return { role, name, level };
  }
  const first = failed.args.find((a) => typeof a === 'string');
  return { role: null, name: typeof first === 'string' ? (first as string) : null, level: null };
}

/** Render the failed locator back to source for annotation/picker messages. */
export function renderFailing(failed: FailedLocatorInfo): string {
  const { role, name } = failedNameAndRole(failed);
  if (failed.method === 'getByRole') {
    return name
      ? `getByRole('${escAttr(role ?? '')}', { name: '${escAttr(name)}' })`
      : `getByRole('${escAttr(role ?? '')}')`;
  }
  return `${failed.method}('${escAttr(name ?? '')}')`;
}

/** Build fresh locator suggestions for a matched candidate, with the failed method's style first. */
function freshSuggestions(
  candidate: { role: string; name: string; level?: number | null },
  failedMethod: string,
): string[] {
  const out: string[] = [];
  const role = candidate.role;
  const name = candidate.name;
  const push = (s: string) => {
    if (!out.includes(s)) out.push(s);
  };

  const levelPart = candidate.level != null ? `, level: ${candidate.level}` : '';
  const roleLoc = `getByRole('${escAttr(role)}', { name: '${escAttr(name)}'${levelPart} })`;
  const textLoc = `getByText('${escAttr(name)}')`;
  const labelLoc = `getByLabel('${escAttr(name)}')`;

  // Same-style first: a broken getByText is re-suggested as getByText where viable.
  if (failedMethod === 'getByText' && SUGG_TEXT_ROLES.has(role)) push(textLoc);
  if (failedMethod === 'getByLabel' && SUGG_FIELD_ROLES.has(role)) push(labelLoc);

  push(roleLoc);
  if (SUGG_TEXT_ROLES.has(role)) push(textLoc);
  else if (SUGG_FIELD_ROLES.has(role)) push(labelLoc);

  return out;
}

/**
 * Best-effort runtime suggestion for a locator that matched nothing: find the
 * element on the *current* page that the failed locator most likely targeted
 * (by accessible name similarity, restricted to the failed role when given) and
 * return fresh locators for it.
 *
 * Unlike the server lookup this has no pre-captured fingerprint — only the
 * failed locator + the live page — so it's a hint, not a guarantee. Returns null
 * for non-name-based locators (testid/CSS), when the targeted name is still
 * present (so the failure wasn't a rename), or when no candidate is confident.
 */
export function suggestLocatorsFromAria(
  failed: FailedLocatorInfo,
  ariaSnapshot: string | null,
): LocatorSuggestion | null {
  if (!ariaSnapshot || !NAME_BASED_METHODS.has(failed.method)) return null;

  const { role, name, level } = failedNameAndRole(failed);
  if (!name) return null;

  const candidates = parseAriaCandidates(ariaSnapshot);
  if (candidates.length === 0) return null;

  const sameRole = role ? candidates.filter((c) => c.role === role) : [];
  let pool = sameRole.length > 0 ? sameRole : candidates;

  // A targeted heading level narrows the pool further — a lone renamed h1
  // among many h2s becomes the single confident candidate. Fall back to all
  // same-role candidates when none share the level (it may have changed too).
  if (level != null && sameRole.length > 0) {
    const sameLevel = sameRole.filter((c) => c.level === level);
    if (sameLevel.length > 0) pool = sameLevel;
  }

  // The targeted name is still on the page → not a rename, nothing to suggest.
  if (pool.some((c) => textSimilarity(c.name, name) >= 0.8)) return null;

  let best: { role: string; name: string | null; level: number | null } | null = null;
  let bestScore = -1;
  for (const c of pool) {
    const s = textSimilarity(c.name, name);
    if (s > bestScore) {
      bestScore = s;
      best = c;
    }
  }
  if (!best || !best.name) return null;
  if (bestScore < 0.2 && pool.length !== 1) return null;

  const suggestions = freshSuggestions({ role: best.role, name: best.name, level: best.level }, failed.method);
  if (suggestions.length === 0) return null;

  return { failing: renderFailing(failed), suggestions };
}

// ── Call-site capture ────────────────────────────────────────────────────────

/**
 * Capture the calling test's source location (`file:line:col`) from the current
 * stack, for stamping onto a locator snapshot. The path is made cwd-relative so
 * it matches the location format Playwright embeds in error messages — which is
 * what the server's exact-match healing lookup (`extractErrorLocation`) parses.
 *
 * Stamping at action *call* time (rather than correlating with `pw:api` step
 * indices at step *end* time) avoids three classes of misalignment: `pw:api`
 * steps with no wrapped locator (e.g. `page.keyboard.press`), cross-worker step
 * interleaving, and concurrent actions reordering by end time.
 *
 * Returns null when no user frame can be identified — the snapshot keeps
 * `location: null` and the server falls back to fingerprint / ARIA lookup.
 */
export function captureCallerLocation(stack: string = new Error().stack ?? ''): string | null {
  const lines = stack.split('\n');
  // The capture machinery's own frames sit at the top of the stack: this module
  // (locator-healing) then the single fixtures-proxy frame that called it. Skip
  // exactly those, so the first remaining frame is the real test call site. A
  // USER file named `fixtures.*` further down the stack must be kept, so the
  // fixtures-proxy frame is only skipped when it directly follows this module.
  let prevWasCaptureModule = false;
  for (let i = 1; i < lines.length; i++) {
    const line = lines[i]!.trim();
    if (!line.startsWith('at')) continue;
    const m = line.match(/^at\s+(?:(.+?)\s+\()?(.+?):(\d+):(\d+)\)?$/);
    if (!m) {
      prevWasCaptureModule = false;
      continue;
    }
    let file = m[2]!;
    if (!file || file.startsWith('node:')) {
      prevWasCaptureModule = false;
      continue;
    }
    file = file.replace(/^file:\/\/\/?/, '');
    // Must look like a source file (has an extension).
    if (!/\.[a-z]+$/i.test(file)) {
      prevWasCaptureModule = false;
      continue;
    }
    // This module — always an internal frame; remember it so the immediately
    // following fixtures-proxy frame can be skipped too.
    if (/[\\/]locator-healing\.[a-z]+$/i.test(file)) {
      prevWasCaptureModule = true;
      continue;
    }
    // The fixtures proxy that called us — `capture-fixtures.*` in this
    // package, `fixtures.*` in the dogfood mirror. Skip only when it directly
    // follows this module, so a user's own `fixtures.*` deeper down is kept.
    if (prevWasCaptureModule && /[\\/](?:capture-)?fixtures\.[a-z]+$/i.test(file)) {
      prevWasCaptureModule = false;
      continue;
    }
    if (/[\\/]node_modules[\\/]/.test(file)) {
      prevWasCaptureModule = false;
      continue;
    }
    let rel = file;
    try {
      rel = path.relative(process.cwd(), file);
    } catch {
      /* keep absolute if relative fails */
    }
    rel = rel.split(path.sep).join('/');
    if (rel.startsWith('./')) rel = rel.slice(2);
    return `${rel}:${m[3]!}:${m[4]!}`;
  }
  return null;
}
