import * as path from 'node:path';
import type { Page, TestInfo } from '@playwright/test';
import {
  approximateAccessibleName,
  generateAlternatives,
  headingLevel,
  isAutoGenerated,
  renderFailing,
  resolveAriaRole,
  type AncestorAnchor,
  type FailedLocatorInfo,
  type LocatorSnapshot,
  type RankedLocator,
  type RolePosition,
  type SelectorCounts,
} from './locator-healing.js';

/**
 * Failure-time locator picker: when enabled (opt-in via the
 * `pickLocatorOnFailure` reporter option / `PIWI_PICK_LOCATOR_ON_FAIL`), a
 * test whose locator action failed gets a picker overlay injected into the
 * still-open page. The flow is guided:
 *
 *  1. **Element** — hover highlights, a click picks. The pick snaps to the
 *     nearest actionable ancestor (a click on the `<span>` inside a button
 *     picks the button), and ↑/↓ walk the DOM tree before the click commits.
 *  2. **Anchors** — the element's ancestors are listed; the human can bless
 *     one or more *stable parents* to scope the locator to, with a live
 *     "matches N" count for the current selection against the failing page.
 *  3. **Confirm** — ranked replacement locators (standard generation merged
 *     with the anchor-scoped candidates) are listed; the human confirms one.
 *
 * The confirmed pick is folded into the failing call site's locator snapshot
 * (so it rides the normal `piwi-locators` wire into the dashboard's healing
 * panel) and attached as `piwi-user-pick` plus a report annotation.
 *
 * Gated exactly like failure-time inspection (`inspect-on-failure.ts`):
 * headed browser, never CI, final attempt only.
 */

/** Element shape the in-page probe returns — structural view of what the picker needs. */
interface ProbedAttrs {
  tagName: string;
  attributes: Record<string, string | null>;
  textContent: string | null;
  center: { x: number; y: number } | null;
  hasLabel?: boolean;
  selectorCounts?: SelectorCounts;
  rolePosition?: RolePosition | null;
  ancestors?: AncestorAnchor[];
}

/**
 * The probe dependency, passed in by the capture fixture to avoid an import
 * cycle. `fn` is the fixture's in-page element probe (`probeElementAttrs`);
 * `el` is a browser-side element, hence `any` (no DOM lib in this package).
 * `arg` is the fixture's `CAPTURED_ATTRS_ARG` — its role maps also drive the
 * anchor step's in-page role resolution.
 */
export interface PickerProbe {
  fn: (el: any, arg: any) => ProbedAttrs;
  arg: unknown;
}

/** An ancestor the human blessed as an anchor, with its in-page uniqueness counts. */
export interface PickedAnchorInfo {
  tag: string;
  /** Hops from the picked element (1 = direct parent). */
  depth: number;
  testId: string | null;
  id: string | null;
  ariaLabel: string | null;
  /** Resolved anchor role (explicit attribute or tag-implied). */
  role: string | null;
  /** Document-wide match count for the anchor's own data-testid. */
  testIdCount?: number;
  /** Document-wide match count for the anchor's own id. */
  idCount?: number;
  /** Document-wide count of same-role elements carrying the same aria-label. */
  labeledRoleCount?: number;
  /** Document-wide count of elements resolving to the anchor's role. */
  roleCount?: number;
  /** Leaf matches (picked element's identity) within this anchor's subtree. */
  scopedLeafCount?: number;
}

/** The picked element's identity used for anchor-scoped candidates. */
export interface PickedLeafInfo {
  role: string | null;
  level: number | null;
}

/** A confirmed pick — everything the fixture records about the human's choice. */
export interface UserPickResult {
  /**
   * The locator this pick replaces. Null when the overlay was opened purely to
   * inspect (`inspectOnFailure` with no identifiable failing locator) — the
   * pick still yields alternatives, but there is nothing to write back to.
   */
  failing: {
    method: string;
    args: unknown[];
    /** The failed locator rendered as source, e.g. `getByText('Pay now')`. */
    rendered: string;
    /** Test call site (`file:line:col`) of the failed action, when captured. */
    location: string | null;
  } | null;
  /** The alternative the human confirmed (also first in `alternatives`). */
  picked: RankedLocator;
  /** Full ranked list for the picked element, the confirmed pick first. */
  alternatives: RankedLocator[];
  /** Wire-shaped element snapshot of the picked element. */
  element: NonNullable<LocatorSnapshot['element']>;
  /** Stable parents the human blessed in the anchor step, when any. */
  anchors?: PickedAnchorInfo[];
}

// ── Deriving the failing locator from an assertion error ─────────────────────
// A locator *action* that throws is captured with its call site (see the
// fixture proxy). An `expect(locator).toBeVisible()` assertion is not an action,
// so nothing is captured — but Playwright's error still names the locator
// (`Locator: …`) and its call site, which is enough to run the picker.

const ANSI_RE = /\[[0-9;]*m/g;

/** Skip a single- or double-quoted string starting at `start`; returns the closing-quote index. */
function endOfString(s: string, start: number): number {
  const q = s[start];
  for (let i = start + 1; i < s.length; i++) {
    if (s[i] === '\\') {
      i++;
      continue;
    }
    if (s[i] === q) return i;
  }
  return s.length - 1;
}

/** Index of the brace matching the `{` at `start`. */
function matchBrace(s: string, start: number): number {
  let depth = 0;
  for (let i = start; i < s.length; i++) {
    if (s[i] === '{') depth++;
    else if (s[i] === '}' && --depth === 0) return i;
  }
  return s.length - 1;
}

/** Parse a Playwright option object literal (`{ name: 'x', level: 2, exact: true }`). */
function parseOptions(src: string): Record<string, unknown> {
  const obj: Record<string, unknown> = {};
  const re = /(\w+)\s*:\s*('(?:\\.|[^'])*'|"(?:\\.|[^"])*"|true|false|-?\d+)/g;
  let m: RegExpExecArray | null;
  while ((m = re.exec(src)) !== null) {
    const key = m[1]!;
    const raw = m[2]!;
    if (raw === 'true') obj[key] = true;
    else if (raw === 'false') obj[key] = false;
    else if (/^-?\d+$/.test(raw)) obj[key] = Number(raw);
    else obj[key] = raw.slice(1, -1).replace(/\\(.)/g, '$1');
  }
  return obj;
}

/** Parse the argument list of a single locator call into its ordered args. */
function parseArgs(inner: string): unknown[] {
  const args: unknown[] = [];
  let i = 0;
  while (i < inner.length) {
    const c = inner[i]!;
    if (c === ' ' || c === ',') {
      i++;
      continue;
    }
    if (c === "'" || c === '"') {
      const end = endOfString(inner, i);
      args.push(inner.slice(i + 1, end).replace(/\\(.)/g, '$1'));
      i = end + 1;
      continue;
    }
    if (c === '{') {
      const end = matchBrace(inner, i);
      args.push(parseOptions(inner.slice(i, end + 1)));
      i = end + 1;
      continue;
    }
    i++; // regex or other token — not needed for identity
  }
  return args;
}

/**
 * The leaf call of a (possibly chained) locator expression — the innermost
 * call identifies the resolved element, mirroring the server's
 * `extractLeafSelector`. Splits on top-level `).`, quote-aware.
 */
function leafExpression(expr: string): string {
  let depth = 0;
  let leafStart = 0;
  for (let i = 0; i < expr.length - 1; i++) {
    const c = expr[i]!;
    if (c === "'" || c === '"') {
      i = endOfString(expr, i);
      continue;
    }
    if (c === '(') depth++;
    else if (c === ')') {
      depth--;
      if (depth === 0 && expr[i + 1] === '.') leafStart = i + 2;
    }
  }
  return expr.slice(leafStart);
}

/** Parse a Playwright locator expression into `{ method, args }` (leaf of any chain). Exported for tests. */
export function parseLeafLocatorExpression(rawExpr: string): { method: string; args: unknown[] } | null {
  const expr = leafExpression(rawExpr.trim());
  const m = /^([A-Za-z]+)\((.*)\)$/s.exec(expr);
  if (!m) return null;
  return { method: m[1]!, args: parseArgs(m[2]!.trim()) };
}

/**
 * Derive the failing locator + call site from a test's error(s) when no locator
 * action was captured (an `expect(...)` assertion failure). Reads the
 * `Locator: …` line Playwright prints and the error's own call location,
 * normalized cwd-relative to match captured snapshot locations. Returns null
 * when no locator can be identified. Exported for tests.
 */
export function deriveFailedLocator(testInfo: TestInfo): FailedLocatorInfo | null {
  const info = testInfo as unknown as {
    errors?: Array<{ message?: string; stack?: string; location?: { file: string; line: number; column: number } }>;
    error?: { message?: string; stack?: string; location?: { file: string; line: number; column: number } };
  };
  const errors = info.errors && info.errors.length > 0 ? info.errors : info.error ? [info.error] : [];
  for (const err of errors) {
    const text = `${err.message ?? ''}\n${err.stack ?? ''}`.replace(ANSI_RE, '');
    const line = /^\s*Locator:\s*(.+)$/m.exec(text);
    if (!line) continue;
    const parsed = parseLeafLocatorExpression(line[1]!.trim());
    if (!parsed) continue;
    const loc = err.location;
    const location = loc
      ? `${path.relative(process.cwd(), loc.file).split(path.sep).join('/')}:${loc.line}:${loc.column}`
      : null;
    return { method: parsed.method, args: parsed.args, location };
  }
  return null;
}

const escStr = (s: string): string => s.replaceAll('\\', '\\\\').replaceAll("'", "\\'");
const cssIdSelector = (id: string): string =>
  /^[A-Za-z_][A-Za-z0-9_-]*$/.test(id) ? `#${id}` : `[id="${id.replaceAll('\\', '\\\\').replaceAll('"', '\\"')}"]`;

/**
 * Per-hook-kind stability score for a user-blessed anchor segment. Sits above
 * the heuristic chain scores (55–72 in `generateAlternatives`) because a
 * person vouched for the anchor.
 */
const ANCHOR_KIND_SCORES = { testid: 80, id: 74, labeledRole: 68, role: 62 } as const;
type AnchorKind = keyof typeof ANCHOR_KIND_SCORES;

/** The strongest document-unique hook an anchor offers, rendered as a chain segment. */
function anchorSegment(
  a: PickedAnchorInfo,
): { code: string; kind: AnchorKind; flatArgs: Record<string, unknown> } | null {
  if (a.testId && a.testIdCount === 1) {
    return { code: `getByTestId('${escStr(a.testId)}')`, kind: 'testid', flatArgs: { anchorTestId: a.testId } };
  }
  if (a.id && !isAutoGenerated(a.id) && a.idCount === 1) {
    const anchorSelector = cssIdSelector(a.id);
    return { code: `locator('${escStr(anchorSelector)}')`, kind: 'id', flatArgs: { anchorSelector } };
  }
  // The anchor's aria-label rides under `anchorName` — never `name`, which the
  // server's fingerprint reader reserves for the LEAF element's accessible name.
  if (a.role && a.ariaLabel && a.labeledRoleCount === 1) {
    return {
      code: `getByRole('${escStr(a.role)}', { name: '${escStr(a.ariaLabel)}' })`,
      kind: 'labeledRole',
      flatArgs: { anchorRole: a.role, anchorName: a.ariaLabel },
    };
  }
  if (a.role && a.roleCount === 1) {
    return { code: `getByRole('${escStr(a.role)}')`, kind: 'role', flatArgs: { anchorRole: a.role } };
  }
  return null;
}

/**
 * Build anchor-scoped candidates from the human-blessed parents. Shapes stay
 * consistent with the heuristic chains in `generateAlternatives` — leaf method
 * `getByRole` with flat anchor args, no leaf `name` key. Single-anchor
 * candidates require the leaf to be unique inside that anchor; with two or
 * more anchors a combined chain is added when the whole chain resolves to
 * exactly one element (`chainLeafCount`). Pure — exported for tests.
 */
export function generateAnchoredAlternatives(
  leaf: PickedLeafInfo,
  anchors: PickedAnchorInfo[],
  chainLeafCount?: number,
): RankedLocator[] {
  if (!leaf.role || anchors.length === 0) return [];
  const out: RankedLocator[] = [];
  const seen = new Set<string>();
  const rolePart = leaf.level != null ? `'${leaf.role}', { level: ${leaf.level} }` : `'${leaf.role}'`;
  const leafArgs: Record<string, unknown> =
    leaf.level != null ? { role: leaf.role, level: leaf.level } : { role: leaf.role };
  const add = (l: RankedLocator) => {
    if (!seen.has(l.locator)) {
      seen.add(l.locator);
      out.push(l);
    }
  };

  for (const anchor of anchors) {
    if (anchor.scopedLeafCount !== 1) continue;
    const seg = anchorSegment(anchor);
    if (!seg) continue;
    add({
      locator: `${seg.code}.getByRole(${rolePart})`,
      method: 'getByRole',
      args: { ...leafArgs, ...seg.flatArgs },
      score: ANCHOR_KIND_SCORES[seg.kind],
    });
  }

  // Combined chain, outermost anchor first — only when the human picked
  // several parents and the whole chain isolates exactly one element.
  if (anchors.length >= 2 && chainLeafCount === 1) {
    const ordered = [...anchors].sort((a, b) => b.depth - a.depth);
    const segments = ordered.map(anchorSegment);
    if (segments.every((s) => s !== null)) {
      const innermost = segments[segments.length - 1]!;
      // A chain is as sturdy as its weakest segment.
      const score = Math.min(...segments.map((s) => ANCHOR_KIND_SCORES[s!.kind]));
      add({
        locator: `${segments.map((s) => s!.code).join('.')}.getByRole(${rolePart})`,
        method: 'getByRole',
        // Flat args describe the innermost anchor (what the healing fingerprint
        // logic understands); the full chain rides along for transparency.
        args: { ...leafArgs, ...innermost.flatArgs, anchorChain: segments.map((s) => s!.code) },
        score,
      });
    }
  }

  return out.sort((a, b) => b.score - a.score);
}

/** Merge candidate lists, first list winning duplicates, sorted by score. Exported for tests. */
export function mergeCandidates(base: RankedLocator[], extra: RankedLocator[]): RankedLocator[] {
  const seen = new Set(base.map((b) => b.locator));
  const merged = [...base];
  for (const e of extra) {
    if (seen.has(e.locator)) continue;
    seen.add(e.locator);
    merged.push(e);
  }
  return merged.sort((a, b) => b.score - a.score);
}

/**
 * Runs inside the browser via `evaluate()` — installs the element-picking
 * overlay: a hover highlight, an instruction banner, and capture-phase
 * listeners that suppress the app's own handlers while picking. The hover
 * target snaps to the nearest actionable ancestor (button/link/field/role/
 * testid) and ↑/↓ walk the DOM chain before the click commits. Resolves
 * through `__piwiPickState` ('picked' | 'skipped') polled from Node; the
 * picked element is parked in `__piwiPickedElement` for an `evaluateHandle`
 * read. Must stay fully self-contained (no module-closure references).
 */
export function installPickerOverlay(arg: { failing: string | null }): void {
  const g = globalThis as any;
  const doc = g.document;
  if (!doc || !doc.body) {
    g.__piwiPickState = 'skipped';
    return;
  }
  const Z = 2147483600;

  const highlight = doc.createElement('div');
  highlight.style.cssText =
    `position:fixed;pointer-events:none;z-index:${Z};display:none;box-sizing:border-box;` +
    'border:2px solid #7c3aed;background:rgba(124,58,237,.12);border-radius:3px;';
  const banner = doc.createElement('div');
  banner.style.cssText =
    `position:fixed;top:12px;left:50%;transform:translateX(-50%);z-index:${Z + 2};` +
    'background:#111827;color:#f9fafb;font:13px/1.5 system-ui,sans-serif;white-space:pre-line;' +
    'padding:10px 16px;border-radius:8px;box-shadow:0 4px 24px rgba(0,0,0,.4);max-width:80vw;';
  const instruction = arg.failing
    ? `Piwi locator picker — click the element that should replace ${arg.failing}.\n`
    : 'Piwi inspector — click any element to generate locators for it.\n';
  banner.textContent = instruction + '↑ parent · ↓ child · Esc skip';
  doc.body.appendChild(highlight);
  doc.body.appendChild(banner);

  // Short descriptor of an element for the banner breadcrumb.
  const describe = (el: any): string => {
    const tag = (el.tagName || '?').toLowerCase();
    const testId = el.getAttribute && el.getAttribute('data-testid');
    if (testId) return `${tag}[data-testid="${testId}"]`;
    if (el.id) return `${tag}#${el.id}`;
    const cls = ((el.getAttribute && el.getAttribute('class')) || '').split(/\s+/).find((c: string) => c.length > 1);
    return cls ? `${tag}.${cls}` : tag;
  };

  // The hover chain: raw target up to (not including) body, capped.
  const buildChain = (raw: any): any[] => {
    const chain: any[] = [];
    let node = raw;
    while (node && chain.length < 15) {
      const tag = (node.tagName || '').toLowerCase();
      if (tag === 'body' || tag === 'html') break;
      chain.push(node);
      node = node.parentElement;
    }
    return chain.length ? chain : [raw];
  };

  // Snap the initial pick to the nearest actionable ancestor — a click lands
  // on the <span> inside a button, but the button is what the test targets.
  const ACTIONABLE_TAGS = ['button', 'a', 'input', 'select', 'textarea', 'summary', 'option'];
  const snapIndex = (chain: any[]): number => {
    for (let i = 0; i < Math.min(chain.length, 4); i++) {
      const el = chain[i];
      const tag = (el.tagName || '').toLowerCase();
      if (ACTIONABLE_TAGS.includes(tag)) return i;
      if (el.getAttribute && (el.getAttribute('role') || el.getAttribute('data-testid'))) return i;
    }
    return 0;
  };

  let chain: any[] = [];
  let idx = 0;
  let lastRaw: any = null;

  const current = (): any => chain[idx] ?? null;
  const refresh = () => {
    const el = current();
    if (!el) {
      highlight.style.display = 'none';
      return;
    }
    const r = el.getBoundingClientRect();
    highlight.style.display = 'block';
    highlight.style.left = r.left + 'px';
    highlight.style.top = r.top + 'px';
    highlight.style.width = r.width + 'px';
    highlight.style.height = r.height + 'px';
    banner.textContent = instruction + `${describe(el)} — click to pick · ↑ parent · ↓ child · Esc skip`;
  };

  const stop = (e: any) => {
    e.preventDefault();
    e.stopImmediatePropagation();
  };
  const isOwn = (el: any) => el === banner || el === highlight || (banner.contains && banner.contains(el));
  const onMove = (e: any) => {
    const raw = e.target;
    if (!raw || isOwn(raw)) {
      highlight.style.display = 'none';
      return;
    }
    if (raw !== lastRaw) {
      lastRaw = raw;
      chain = buildChain(raw);
      idx = snapIndex(chain);
    }
    refresh();
  };
  const onClick = (e: any) => {
    stop(e);
    const el = current();
    if (!el || isOwn(e.target)) return;
    g.__piwiPickedElement = el;
    g.__piwiPickState = 'picked';
    removeListeners();
    highlight.style.display = 'none';
    banner.textContent = 'Piwi locator picker — analyzing element…';
  };
  const onKey = (e: any) => {
    if (e.key === 'Escape') {
      stop(e);
      g.__piwiPickState = 'skipped';
      cleanup();
      return;
    }
    if (e.key === 'ArrowUp' || e.key === 'ArrowDown') {
      stop(e);
      if (e.key === 'ArrowUp') idx = Math.min(idx + 1, chain.length - 1);
      else idx = Math.max(idx - 1, 0);
      refresh();
    }
  };
  // Suppress the app's own pointer handlers while picking — a pick must never
  // navigate or mutate the failing page under inspection.
  const suppressed = ['mousedown', 'mouseup', 'pointerdown', 'pointerup', 'auxclick', 'dblclick'];
  const removeListeners = () => {
    doc.removeEventListener('mousemove', onMove, true);
    doc.removeEventListener('click', onClick, true);
    doc.removeEventListener('keydown', onKey, true);
    for (const t of suppressed) doc.removeEventListener(t, stop, true);
  };
  const cleanup = () => {
    removeListeners();
    highlight.remove();
    banner.remove();
  };
  g.__piwiPickCleanup = cleanup;
  doc.addEventListener('mousemove', onMove, true);
  doc.addEventListener('click', onClick, true);
  doc.addEventListener('keydown', onKey, true);
  for (const t of suppressed) doc.addEventListener(t, stop, true);
}

/**
 * Runs inside the browser via `evaluate()` — the anchor step: lists the picked
 * element's ancestors so the human can bless one or more stable parents to
 * scope the locator to. Each row shows the ancestor's strongest hook and how
 * many leaf matches it contains; the footer shows a live "matches N" count for
 * the combined selection, recomputed against the real failing page on every
 * toggle (exactly 1 = green). Hovering a row outlines that ancestor in the
 * page. Resolves through `__piwiAnchorState` ('done' | 'skipped'); selected
 * anchors land in `__piwiPickAnchors` (+ `__piwiPickChainCount`). Role
 * resolution reuses the maps passed in `arg` (single source of truth in
 * locator-healing.ts). Must stay fully self-contained.
 */
export function showAnchorPicker(arg: {
  tagRoles: Record<string, string>;
  inputRoles: Record<string, string>;
  roleSources: string;
  leafRole: string;
  leafLevel: number | null;
  leafTestId: string | null;
}): void {
  const g = globalThis as any;
  const doc = g.document;
  const el = g.__piwiPickedElement;
  if (!doc || !doc.body || !el) {
    g.__piwiAnchorState = 'skipped';
    return;
  }
  const Z = 2147483600;
  const { tagRoles, inputRoles, roleSources, leafRole, leafLevel, leafTestId } = arg;

  const roleOf = (n: any): string | null => {
    const explicit = n.getAttribute && n.getAttribute('role');
    if (explicit) return explicit;
    const tag = (n.tagName || '').toLowerCase();
    if (tag === 'input') return inputRoles[(n.getAttribute('type') || 'text').toLowerCase()] ?? 'textbox';
    if (tag === 'select') return n.getAttribute('multiple') != null ? 'listbox' : 'combobox';
    if (tag === 'a') return n.getAttribute('href') != null ? 'link' : null;
    return tagRoles[tag] ?? null;
  };
  const levelOf = (n: any): number | null => {
    const m = /^h([1-6])$/.exec((n.tagName || '').toLowerCase());
    if (m) return Number(m[1]);
    const al = n.getAttribute && n.getAttribute('aria-level');
    return al && /^\d+$/.test(al) ? Number(al) : null;
  };

  // Leaf matches inside a scope: same data-testid when the element has one,
  // otherwise same resolved role (level-scoped for headings).
  const leafMatches = (scope: any): number => {
    try {
      if (leafTestId) return scope.querySelectorAll(`[data-testid=${JSON.stringify(leafTestId)}]`).length;
      const nodes = scope.querySelectorAll(roleSources);
      if (nodes.length > 2000) return -1;
      let matched = 0;
      for (let i = 0; i < nodes.length; i++) {
        const n = nodes[i];
        if (roleOf(n) !== leafRole) continue;
        if (leafLevel != null && levelOf(n) !== leafLevel) continue;
        matched++;
      }
      return matched;
    } catch {
      return -1;
    }
  };

  // Document-wide role nodes, computed once for anchor uniqueness counts.
  let roleNodes: any[] = [];
  try {
    const all = doc.querySelectorAll(roleSources);
    if (all.length <= 4000) roleNodes = Array.from(all);
  } catch {
    roleNodes = [];
  }
  const count = (sel: string): number | undefined => {
    try {
      return doc.querySelectorAll(sel).length;
    } catch {
      return undefined;
    }
  };

  // Ancestor rows, nearest parent first, up to (not including) body.
  interface Row {
    node: any;
    info: any;
    hookLabel: string;
    selectable: boolean;
  }
  const rows: Row[] = [];
  let node = el.parentElement;
  let depth = 0;
  while (node && depth < 12) {
    depth++;
    const tag = (node.tagName || '').toLowerCase();
    if (tag === 'body' || tag === 'html') break;
    const testId = node.getAttribute('data-testid');
    const id = node.getAttribute('id');
    const ariaLabel = node.getAttribute('aria-label');
    const role = roleOf(node);
    const info: any = { tag, depth, testId: testId || null, id: id || null, ariaLabel: ariaLabel || null, role };
    if (testId) info.testIdCount = count(`[data-testid=${JSON.stringify(testId)}]`);
    if (id) {
      try {
        info.idCount = count(`#${doc.defaultView.CSS.escape(id)}`);
      } catch {
        // Keep idCount undefined — the Node side treats it as non-unique.
      }
    }
    if (role) {
      let roleCount = 0;
      let labeledCount = 0;
      for (const n of roleNodes) {
        if (roleOf(n) !== role) continue;
        roleCount++;
        if (ariaLabel && n.getAttribute && n.getAttribute('aria-label') === ariaLabel) labeledCount++;
      }
      info.roleCount = roleCount;
      if (ariaLabel) info.labeledRoleCount = labeledCount;
    }
    info.scopedLeafCount = leafMatches(node);

    const hookLabel = testId
      ? `data-testid="${testId}"`
      : id
        ? `#${id}`
        : ariaLabel && role
          ? `${role} "${ariaLabel}"`
          : role
            ? `role ${role}`
            : 'no stable hook';
    rows.push({
      node,
      info,
      hookLabel,
      selectable: !!(testId || id || (role && (ariaLabel || info.roleCount === 1))),
    });
    node = node.parentElement;
  }

  if (rows.length === 0) {
    g.__piwiAnchorState = 'skipped';
    return;
  }

  const outline = doc.createElement('div');
  outline.style.cssText =
    `position:fixed;pointer-events:none;z-index:${Z};box-sizing:border-box;` +
    'border:2px solid #22c55e;border-radius:3px;display:none;';
  const pickedOutline = doc.createElement('div');
  const pr = el.getBoundingClientRect();
  pickedOutline.style.cssText =
    `position:fixed;pointer-events:none;z-index:${Z};box-sizing:border-box;` +
    'border:2px solid #7c3aed;background:rgba(124,58,237,.10);border-radius:3px;' +
    `left:${pr.left}px;top:${pr.top}px;width:${pr.width}px;height:${pr.height}px;`;
  const panel = doc.createElement('div');
  panel.style.cssText =
    `position:fixed;top:12px;right:12px;z-index:${Z + 3};width:340px;max-height:82vh;overflow:auto;` +
    'background:#111827;color:#f9fafb;border-radius:10px;padding:16px;' +
    'font:12px/1.5 system-ui,sans-serif;box-shadow:0 8px 40px rgba(0,0,0,.5);';
  const title = doc.createElement('div');
  title.style.cssText = 'font-weight:600;font-size:13px;margin-bottom:2px;';
  title.textContent = 'Scope to stable parents (optional)';
  const sub = doc.createElement('div');
  sub.style.cssText = 'color:#9ca3af;margin-bottom:10px;';
  sub.textContent = 'Pick one or more parents to anchor the locator to. Hover a row to see the parent.';
  panel.appendChild(title);
  panel.appendChild(sub);

  const selected = new Set<number>();
  const footer = doc.createElement('div');
  footer.style.cssText = 'margin:10px 0;font-weight:600;';

  // Segment priority mirrors the Node-side generator so the live count and the
  // emitted chain agree: testid > id > labeled role > bare role.
  const segMatches = (scope: any, info: any): any[] => {
    try {
      if (info.testId) return Array.from(scope.querySelectorAll(`[data-testid=${JSON.stringify(info.testId)}]`));
      if (info.id) return Array.from(scope.querySelectorAll(`#${doc.defaultView.CSS.escape(info.id)}`));
      const nodes = Array.from(scope.querySelectorAll(roleSources));
      if (nodes.length > 2000) return [];
      return nodes.filter(
        (n: any) =>
          roleOf(n) === info.role &&
          (!info.ariaLabel || (n.getAttribute && n.getAttribute('aria-label') === info.ariaLabel)),
      );
    } catch {
      return [];
    }
  };

  const chainCount = (): number => {
    const chosen = rows.filter((_, i) => selected.has(i)).sort((a, b) => b.info.depth - a.info.depth);
    if (chosen.length === 0) return -1;
    let scopes: any[] = [doc];
    for (const row of chosen) {
      const next: any[] = [];
      for (const s of scopes) next.push(...segMatches(s, row.info));
      scopes = next.slice(0, 200);
      if (scopes.length === 0) return 0;
    }
    let total = 0;
    for (const s of scopes) {
      const c = leafMatches(s);
      if (c > 0) total += c;
      if (total > 50) return total;
    }
    return total;
  };

  const refreshFooter = () => {
    if (selected.size === 0) {
      footer.textContent = 'No parents selected — standard alternatives only.';
      footer.style.color = '#9ca3af';
      g.__piwiPickChainCount = undefined;
      return;
    }
    const c = chainCount();
    g.__piwiPickChainCount = c;
    if (c === 1) {
      footer.textContent = '✓ Selection matches exactly 1 element';
      footer.style.color = '#4ade80';
    } else {
      footer.textContent = c < 0 ? 'Match count unavailable' : `✗ Selection matches ${c} elements`;
      footer.style.color = '#fbbf24';
    }
  };

  rows.forEach((row, i) => {
    const line = doc.createElement('label');
    line.style.cssText =
      'display:flex;align-items:center;gap:8px;padding:6px 8px;border:1px solid #374151;border-radius:6px;' +
      `margin-bottom:6px;cursor:${row.selectable ? 'pointer' : 'default'};opacity:${row.selectable ? '1' : '.45'};`;
    const box = doc.createElement('input');
    box.type = 'checkbox';
    box.disabled = !row.selectable;
    const text = doc.createElement('span');
    text.style.cssText = 'flex:1;min-width:0;';
    const code = doc.createElement('code');
    code.style.cssText = 'display:block;font:11px ui-monospace,monospace;color:#e5e7eb;word-break:break-all;';
    code.textContent = `<${row.info.tag}> ${row.hookLabel}`;
    const hint = doc.createElement('span');
    hint.style.cssText = 'color:#9ca3af;';
    hint.textContent = row.selectable
      ? row.info.scopedLeafCount === 1
        ? 'contains exactly 1 matching element'
        : `contains ${row.info.scopedLeafCount ?? '?'} matching elements`
      : 'add a data-testid to make this usable';
    text.appendChild(code);
    text.appendChild(hint);
    line.appendChild(box);
    line.appendChild(text);
    line.addEventListener('mouseenter', () => {
      const r = row.node.getBoundingClientRect();
      outline.style.display = 'block';
      outline.style.left = r.left + 'px';
      outline.style.top = r.top + 'px';
      outline.style.width = r.width + 'px';
      outline.style.height = r.height + 'px';
    });
    line.addEventListener('mouseleave', () => {
      outline.style.display = 'none';
    });
    box.addEventListener('change', () => {
      if (box.checked) selected.add(i);
      else selected.delete(i);
      refreshFooter();
    });
    panel.appendChild(line);
  });

  panel.appendChild(footer);

  const cleanup = () => {
    doc.removeEventListener('keydown', onKey, true);
    panel.remove();
    outline.remove();
    pickedOutline.remove();
  };
  const done = (state: 'done' | 'skipped') => {
    g.__piwiPickAnchors = state === 'done' ? rows.filter((_, i) => selected.has(i)).map((r) => r.info) : [];
    g.__piwiAnchorState = state;
    cleanup();
  };
  const onKey = (e: any) => {
    if (e.key !== 'Escape') return;
    e.preventDefault();
    e.stopImmediatePropagation();
    done('skipped');
  };

  const buttonRow = doc.createElement('div');
  buttonRow.style.cssText = 'display:flex;gap:8px;margin-top:4px;';
  const useBtn = doc.createElement('button');
  useBtn.style.cssText =
    'flex:1;background:#7c3aed;color:#fff;border:none;border-radius:6px;padding:8px;cursor:pointer;font:600 12px system-ui;';
  useBtn.textContent = 'Use selected parents';
  useBtn.addEventListener('click', (e: any) => {
    e.preventDefault();
    e.stopImmediatePropagation();
    done(selected.size > 0 ? 'done' : 'skipped');
  });
  const skipBtn = doc.createElement('button');
  skipBtn.style.cssText =
    'background:none;border:1px solid #374151;color:#9ca3af;border-radius:6px;padding:8px 10px;cursor:pointer;font:12px system-ui;';
  skipBtn.textContent = 'Skip (Esc)';
  skipBtn.addEventListener('click', (e: any) => {
    e.preventDefault();
    e.stopImmediatePropagation();
    done('skipped');
  });
  buttonRow.appendChild(useBtn);
  buttonRow.appendChild(skipBtn);
  panel.appendChild(buttonRow);

  refreshFooter();
  g.__piwiAnchorCleanup = cleanup;
  doc.addEventListener('keydown', onKey, true);
  doc.body.appendChild(pickedOutline);
  doc.body.appendChild(outline);
  doc.body.appendChild(panel);
}

/**
 * Runs inside the browser via `evaluate()` — replaces the pick overlay with a
 * confirmation panel listing the ranked replacement locators. The chosen index
 * lands in `__piwiPickChoice` (-1 = skipped), polled from Node. Must stay
 * fully self-contained.
 */
export function showPickerChoices(arg: {
  failing: string | null;
  choices: Array<{ locator: string; score: number }>;
}): void {
  const g = globalThis as any;
  const doc = g.document;
  if (!doc || !doc.body) {
    g.__piwiPickChoice = -1;
    return;
  }
  const Z = 2147483600;

  const wrap = doc.createElement('div');
  wrap.style.cssText =
    `position:fixed;inset:0;z-index:${Z + 3};background:rgba(0,0,0,.45);` +
    'display:flex;align-items:center;justify-content:center;font:13px/1.5 system-ui,sans-serif;';
  const panel = doc.createElement('div');
  panel.style.cssText =
    'background:#111827;color:#f9fafb;border-radius:10px;padding:20px;' +
    'max-width:640px;width:90vw;max-height:70vh;overflow:auto;box-shadow:0 8px 40px rgba(0,0,0,.5);';
  const title = doc.createElement('div');
  title.style.cssText = 'font-weight:600;margin-bottom:4px;';
  title.textContent = arg.failing ? 'Pick a replacement locator' : 'Pick a locator';
  const sub = doc.createElement('div');
  sub.style.cssText = 'color:#9ca3af;margin-bottom:12px;';
  sub.textContent = arg.failing
    ? `Replaces ${arg.failing} — ranked by stability score.`
    : 'For the element you picked — ranked by stability score.';
  panel.appendChild(title);
  panel.appendChild(sub);

  const done = (choice: number) => {
    g.__piwiPickChoice = choice;
    doc.removeEventListener('keydown', onKey, true);
    wrap.remove();
  };
  const onKey = (e: any) => {
    if (e.key !== 'Escape') return;
    e.preventDefault();
    e.stopImmediatePropagation();
    done(-1);
  };

  arg.choices.forEach((c, i) => {
    const btn = doc.createElement('button');
    btn.style.cssText =
      'display:flex;justify-content:space-between;align-items:center;gap:12px;width:100%;' +
      'text-align:left;background:#1f2937;color:#e5e7eb;border:1px solid #374151;border-radius:6px;' +
      'padding:8px 12px;margin:0 0 8px;cursor:pointer;font:12px/1.5 ui-monospace,SFMono-Regular,Menlo,monospace;';
    const code = doc.createElement('span');
    code.textContent = c.locator;
    code.style.cssText = 'word-break:break-all;';
    const score = doc.createElement('span');
    score.textContent = String(c.score);
    score.style.cssText = 'color:#a78bfa;flex-shrink:0;';
    btn.appendChild(code);
    btn.appendChild(score);
    btn.addEventListener('click', (e: any) => {
      e.preventDefault();
      e.stopImmediatePropagation();
      done(i);
    });
    panel.appendChild(btn);
  });

  const skip = doc.createElement('button');
  skip.style.cssText =
    'background:none;border:none;color:#9ca3af;cursor:pointer;padding:6px 0 0;font:12px system-ui,sans-serif;';
  skip.textContent = 'Skip — keep the failure as-is (Esc)';
  skip.addEventListener('click', (e: any) => {
    e.preventDefault();
    e.stopImmediatePropagation();
    done(-1);
  });
  panel.appendChild(skip);

  doc.addEventListener('keydown', onKey, true);
  wrap.appendChild(panel);
  doc.body.appendChild(wrap);
}

/** Best-effort in-page cleanup of every picker artifact. */
async function cleanupPicker(page: Page): Promise<void> {
  try {
    await page.evaluate(() => {
      const g = globalThis as any;
      if (typeof g.__piwiPickCleanup === 'function') g.__piwiPickCleanup();
      if (typeof g.__piwiAnchorCleanup === 'function') g.__piwiAnchorCleanup();
      delete g.__piwiPickCleanup;
      delete g.__piwiAnchorCleanup;
      delete g.__piwiPickState;
      delete g.__piwiPickChoice;
      delete g.__piwiPickedElement;
      delete g.__piwiAnchorState;
      delete g.__piwiPickAnchors;
      delete g.__piwiPickChainCount;
    });
  } catch {
    // The page may be gone — nothing left to clean.
  }
}

/**
 * Drive the full pick flow on the failing page: element pick (snap +
 * tree-walk), optional stable-parent anchoring with live match counts, ranked
 * candidates (standard generation merged with anchor-scoped chains), and a
 * final confirmation. The test timeout is lifted while waiting. Returns null
 * when skipped or when anything breaks — the picker must never mask the
 * test's own failure.
 */
export async function runLocatorPicker(
  page: Page,
  testInfo: TestInfo,
  failed: FailedLocatorInfo | null,
  probe: PickerProbe,
): Promise<UserPickResult | null> {
  try {
    testInfo.setTimeout(0);
    const rendered = failed ? renderFailing(failed) : null;
    console.log(
      `\n[piwi] "${testInfo.title}" ${testInfo.status} — ${rendered ? 'locator picker' : 'inspector'} open in the ` +
        `browser: ${
          rendered
            ? `click the element that should replace ${rendered}`
            : 'click any element to generate ' + 'locators for it'
        } (↑/↓ to select a parent/child, Esc to skip).`,
    );

    await page.evaluate(installPickerOverlay, { failing: rendered });
    await page.waitForFunction(() => (globalThis as any).__piwiPickState !== undefined, undefined, {
      timeout: 0,
      polling: 250,
    });
    const state = (await page.evaluate(() => (globalThis as any).__piwiPickState)) as string;
    if (state !== 'picked') {
      await cleanupPicker(page);
      return null;
    }

    const handle = await page.evaluateHandle(() => (globalThis as any).__piwiPickedElement);
    const attrs = (await (handle as any).evaluate(probe.fn, probe.arg)) as ProbedAttrs;
    await handle.dispose();

    const accessibleName = approximateAccessibleName({ ...attrs, accessibleName: null });
    const role = resolveAriaRole({ ...attrs, accessibleName });
    const level = headingLevel({ ...attrs, accessibleName }, role);

    // Anchor step — only when the leaf has a role (anchor-scoped chains are
    // role-leaf locators, matching the heuristic chain shapes).
    let anchors: PickedAnchorInfo[] = [];
    let chainLeafCount: number | undefined;
    if (role) {
      const probeArg = probe.arg as {
        tagRoles: Record<string, string>;
        inputRoles: Record<string, string>;
        roleSources: string;
      };
      await page.evaluate(showAnchorPicker, {
        tagRoles: probeArg.tagRoles,
        inputRoles: probeArg.inputRoles,
        roleSources: probeArg.roleSources,
        leafRole: role,
        leafLevel: level,
        leafTestId: attrs.attributes['data-testid'] ?? null,
      });
      await page.waitForFunction(() => (globalThis as any).__piwiAnchorState !== undefined, undefined, {
        timeout: 0,
        polling: 250,
      });
      const anchorResult = (await page.evaluate(() => {
        const g = globalThis as any;
        return { state: g.__piwiAnchorState, anchors: g.__piwiPickAnchors ?? [], chainCount: g.__piwiPickChainCount };
      })) as { state: string; anchors: PickedAnchorInfo[]; chainCount?: number };
      if (anchorResult.state === 'done' && anchorResult.anchors.length > 0) {
        anchors = anchorResult.anchors;
        chainLeafCount = anchorResult.chainCount;
      }
    }

    const ranked = mergeCandidates(
      generateAlternatives({ ...attrs, accessibleName }),
      generateAnchoredAlternatives({ role, level }, anchors, chainLeafCount),
    );
    if (ranked.length === 0) {
      console.log('[piwi] No stable locator could be generated for the picked element — nothing recorded.');
      await cleanupPicker(page);
      return null;
    }

    await page.evaluate(showPickerChoices, {
      failing: rendered,
      choices: ranked.map((r) => ({ locator: r.locator, score: r.score })),
    });
    await page.waitForFunction(() => (globalThis as any).__piwiPickChoice !== undefined, undefined, {
      timeout: 0,
      polling: 250,
    });
    const choice = (await page.evaluate(() => (globalThis as any).__piwiPickChoice)) as number;
    await cleanupPicker(page);
    if (typeof choice !== 'number' || choice < 0 || choice >= ranked.length) return null;

    const picked: RankedLocator = { ...ranked[choice]!, pickedByUser: true };
    const alternatives = [picked, ...ranked.filter((_, i) => i !== choice)];
    const element: UserPickResult['element'] = {
      tagName: attrs.tagName,
      attributes: attrs.attributes,
      textContent: attrs.textContent,
      accessibleName,
      center: attrs.center,
      ...(attrs.rolePosition ? { rolePosition: attrs.rolePosition } : {}),
      ...(attrs.ancestors && attrs.ancestors.length > 0 ? { ancestors: attrs.ancestors } : {}),
    };

    const location = failed?.location ?? null;
    console.log(
      failed
        ? `[piwi] Replacement picked for ${rendered}${location ? ` at ${location}` : ''}:\n[piwi]   ${picked.locator}`
        : `[piwi] Locator picked while inspecting:\n[piwi]   ${picked.locator}`,
    );
    return {
      failing: failed ? { method: failed.method, args: failed.args, rendered: rendered!, location } : null,
      picked,
      alternatives,
      element,
      ...(anchors.length > 0 ? { anchors } : {}),
    };
  } catch {
    return null;
  }
}

/**
 * Fold a confirmed pick into the captured snapshots: the failed action's
 * placeholder (same call site, no element — capture never probes an action
 * that threw) is filled with the picked element and the confirmed-first
 * alternative list, so the pick rides the normal `piwi-locators` attachment
 * into the dashboard's `locator_snapshots` and healing panel.
 *
 * A failed locator *action* left a placeholder at its call site (same location,
 * no element) — that placeholder is filled in place. An assertion failure left
 * no placeholder (no action ran), so a fresh snapshot is appended under the
 * failing locator's location and signature instead, so the pick still reaches
 * `locator_snapshots`. No-op only when the failing locator has no location.
 * Exported for tests.
 */
export function applyPickToSnapshots(snapshots: LocatorSnapshot[], pick: UserPickResult): boolean {
  // No failing locator (pure inspect pick) or no call site — nothing to key on.
  if (!pick.failing?.location) return false;
  const failing = pick.failing;
  for (let i = snapshots.length - 1; i >= 0; i--) {
    const snap = snapshots[i]!;
    if (snap.location !== failing.location || snap.element) continue;
    snapshots[i] = {
      location: snap.location,
      used: snap.used,
      element: pick.element,
      alternatives: pick.alternatives.slice(0, 10),
    };
    return true;
  }
  // No placeholder — an assertion failure. Append a snapshot keyed to the
  // failing locator so the healing lookup finds the pick by location/signature.
  snapshots.push({
    location: failing.location,
    used: {
      method: failing.method,
      args: failing.args,
      raw: `${failing.method}(${JSON.stringify(failing.args)})`,
    },
    element: pick.element,
    alternatives: pick.alternatives.slice(0, 10),
  });
  return true;
}
