import { describe, test, expect } from 'vitest';
import { readFileSync, existsSync, readdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join, relative } from 'node:path';
import { MCP_TOOL_DEFS } from '#shared/mcp-tools';

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), '..', '..', '..', '..');
const read = (relative: string) => readFileSync(join(repoRoot, relative), 'utf8');

// The one line the project describes itself with. AGENTS.md names the surfaces
// that must carry it; these are the ones that live in the repository.
const POSITIONING = [
  'CI throws away every report it makes.',
  'Piwi keeps them',
  'groups the failures by root cause',
  'scores the flaky tests',
  'finds the locator you should have used',
  'Self-hosted, MIT, zero telemetry',
];

const POSITIONING_SURFACES = ['README.md', 'DOCKER_HUB.md', 'apps/docs/index.md', 'apps/docs/.vitepress/config.mts'];

describe('positioning line', () => {
  test.each(POSITIONING_SURFACES)('%s carries every clause', (relative) => {
    // Prose wraps, so compare against a single-spaced copy: a clause split
    // across two source lines is still the same sentence to a reader.
    const contents = read(relative).replace(/\s+/g, ' ');
    for (const clause of POSITIONING) {
      expect(contents, `${relative} is missing "${clause}" — see AGENTS.md#documentation`).toContain(clause);
    }
  });
});

describe('documented counts', () => {
  test('every page claiming an MCP tool count states the real one', () => {
    const claim = new RegExp(`\\b${MCP_TOOL_DEFS.length}\\b tools`);
    for (const relative of ['apps/docs/mcp.md', 'apps/docs/comparison.md', 'ROADMAP.md']) {
      const stated = read(relative).match(/\b(\d+) tools\b/);
      if (!stated) continue;
      expect(read(relative), `${relative} says "${stated[0]}", there are ${MCP_TOOL_DEFS.length}`).toMatch(claim);
    }
  });

  test('every registered MCP tool is documented in apps/docs/mcp.md', () => {
    const contents = read('apps/docs/mcp.md');
    for (const { name } of MCP_TOOL_DEFS) {
      expect(contents, `apps/docs/mcp.md has no entry for \`${name}\``).toContain(`\`${name}\``);
    }
  });
});

describe('docs pages the app deep-links into', () => {
  // help-content.ts and a handful of components build docs URLs from bare
  // string literals that nothing else validates, so a renamed heading breaks
  // them silently in production.
  const slug = (heading: string) =>
    heading
      .toLowerCase()
      .replace(/`/g, '')
      .replace(/\*\*/g, '')
      .replace(/\[([^\]]*)\]\([^)]*\)/g, '$1')
      .replace(/[^\w\- ]+/g, '')
      .trim()
      .replace(/\s+/g, '-');

  // Every .vue/.ts file under app/ — any of them may carry a `doc: '…'`
  // registry field or a static `DocLink to="…"`.
  const sources = (function walk(dir: string): string[] {
    return readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
      const path = join(dir, entry.name);
      if (entry.isDirectory()) return walk(path);
      return /\.(vue|ts)$/.test(entry.name) ? [relative(repoRoot, path)] : [];
    });
  })(join(repoRoot, 'apps/application/app'));

  const targets = [
    ...new Set(
      sources.flatMap((source) => {
        const contents = read(source);
        return [
          ...[...contents.matchAll(/doc: '([^']+)'/g)].map((m) => m[1]!),
          ...[...contents.matchAll(/DocLink\s+to="([^"]+)"/g)].map((m) => m[1]!),
        ];
      }),
    ),
  ];

  test('there are links to check', () => {
    expect(targets.length).toBeGreaterThan(0);
  });

  test.each(targets)('%s resolves to a page and heading', (target) => {
    const [page, anchor] = target.split('#');
    // configuration.md is generated by the docs build and gitignored, so it is
    // only present when the docs have been built — skip rather than fail.
    const path = join(repoRoot, 'apps/docs', `${page}.md`);
    if (page === 'configuration' && !existsSync(path)) return;

    expect(existsSync(path), `no apps/docs/${page}.md`).toBe(true);
    if (!anchor) return;

    const headings = [...readFileSync(path, 'utf8').matchAll(/^#{2,4} (.+)$/gm)].map((m) => slug(m[1]!));
    expect(headings, `apps/docs/${page}.md has no heading anchored #${anchor}`).toContain(anchor);
  });
});
