import { describe, test, expect } from 'vitest';
import { readFileSync, existsSync, readdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join, relative } from 'node:path';
import { MCP_TOOL_DEFS } from '#shared/mcp-tools';

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), '..', '..', '..', '..');
const read = (relative: string) => readFileSync(join(repoRoot, relative), 'utf8');

// The one line the project describes itself with. AGENTS.md names the surfaces
// that must carry it; these are the ones that live in the repository.
const POSITIONING = [
  'CI throws away every report it makes.',
  'Piwi keeps them',
  'groups the failures by root cause',
  'scores the flaky tests',
  'finds the locator you should have used',
  'Self-hosted, MIT, zero telemetry',
];

const POSITIONING_SURFACES = ['README.md', 'DOCKER_HUB.md', 'apps/docs/index.md', 'apps/docs/.vitepress/config.mts'];

describe('positioning line', () => {
  test.each(POSITIONING_SURFACES)('%s carries every clause', (relative) => {
    // Prose wraps, so compare against a single-spaced copy: a clause split
    // across two source lines is still the same sentence to a reader.
    const contents = read(relative).replace(/\s+/g, ' ');
    for (const clause of POSITIONING) {
      expect(contents, `${relative} is missing "${clause}" — see AGENTS.md#documentation`).toContain(clause);
    }
  });
});

describe('documented counts', () => {
  // Every page on the docs site (the generated configuration.md included,
  // when built) plus the repository-level pages that repeat the number.
  const docsPages = (function walk(dir: string): string[] {
    return readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
      if (entry.name === 'node_modules' || entry.name.startsWith('.')) return [];
      const path = join(dir, entry.name);
      if (entry.isDirectory()) return walk(path);
      return entry.name.endsWith('.md') ? [relative(repoRoot, path)] : [];
    });
  })(join(repoRoot, 'apps/docs'));
  const COUNT_SURFACES = [...docsPages, 'README.md', 'ROADMAP.md', 'DOCKER_HUB.md'];

  test.each(COUNT_SURFACES)('%s states the real MCP tool count, if it states one', (relative) => {
    for (const [claim, stated] of read(relative).matchAll(/\b(\d+) tools\b/g)) {
      expect(Number(stated), `${relative} says "${claim}", there are ${MCP_TOOL_DEFS.length}`).toBe(
        MCP_TOOL_DEFS.length,
      );
    }
  });

  test('every registered MCP tool is documented in apps/docs/mcp.md', () => {
    const contents = read('apps/docs/mcp.md');
    for (const { name } of MCP_TOOL_DEFS) {
      expect(contents, `apps/docs/mcp.md has no entry for \`${name}\``).toContain(`\`${name}\``);
    }
  });
});

describe('docs pages the app deep-links into', () => {
  // help-content.ts and a handful of components build docs URLs from bare
  // string literals that nothing else validates, so a renamed heading breaks
  // them silently in production.
  const slug = (heading: string) =>
    heading
      .toLowerCase()
      .replace(/`/g, '')
      .replace(/\*\*/g, '')
      .replace(/\[([^\]]*)\]\([^)]*\)/g, '$1')
      .replace(/[^\w\- ]+/g, '')
      .trim()
      .replace(/\s+/g, '-');

  // Every .vue/.ts file under app/ — any of them may carry a `doc: '…'`
  // registry field or a static `DocLink to="…"`.
  const sources = (function walk(dir: string): string[] {
    return readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
      const path = join(dir, entry.name);
      if (entry.isDirectory()) return walk(path);
      return /\.(vue|ts)$/.test(entry.name) ? [relative(repoRoot, path)] : [];
    });
  })(join(repoRoot, 'apps/application/app'));

  const targets = [
    ...new Set(
      sources.flatMap((source) => {
        const contents = read(source);
        return [
          ...[...contents.matchAll(/doc: '([^']+)'/g)].map((m) => m[1]!),
          ...[...contents.matchAll(/DocLink\s+to="([^"]+)"/g)].map((m) => m[1]!),
        ];
      }),
    ),
  ];

  test('there are links to check', () => {
    expect(targets.length).toBeGreaterThan(0);
  });

  test.each(targets)('%s resolves to a page and heading', (target) => {
    const [page, anchor] = target.split('#');
    // configuration.md is generated by the docs build and gitignored, so it is
    // only present when the docs have been built — skip rather than fail.
    const path = join(repoRoot, 'apps/docs', `${page}.md`);
    if (page === 'configuration' && !existsSync(path)) return;

    expect(existsSync(path), `no apps/docs/${page}.md`).toBe(true);
    if (!anchor) return;

    const headings = [...readFileSync(path, 'utf8').matchAll(/^#{2,4} (.+)$/gm)].map((m) => slug(m[1]!));
    expect(headings, `apps/docs/${page}.md has no heading anchored #${anchor}`).toContain(anchor);
  });
});

describe('single-source snippets', () => {
  // Shared blocks live once under apps/docs/snippets/ and are pulled into docs
  // pages with VitePress code includes (`<<< @/snippets/…`). Surfaces that
  // cannot include a file — the repo README, the npm package READMEs, the
  // Docker Hub page, and inline references in prose — carry a literal copy
  // instead; this guard fails when such a copy drifts from the canonical
  // snippet, the same way the positioning check keeps that one line in sync
  // across surfaces. The canonical text is compared trimmed, so a one-liner
  // embedded inline in a sentence still matches.
  const SNIPPET_COPIES: Record<string, readonly string[]> = {
    'apps/docs/snippets/fixtures.ts': ['README.md', 'packages/reporter/README.md'],
    'apps/docs/snippets/secret.sh': ['README.md', 'DOCKER_HUB.md', 'packages/server/README.md'],
  };

  for (const [snippet, surfaces] of Object.entries(SNIPPET_COPIES)) {
    const canonical = read(snippet).trim();
    test.each(surfaces)(`${snippet} → %s carries it verbatim`, (surface) => {
      expect(
        read(surface),
        `${surface} has drifted from ${snippet} — paste the snippet in byte for byte, or convert the surface to a VitePress include`,
      ).toContain(canonical);
    });
  }
});
