/**
 * Locator generation — pure functions for building ranked alternative locators
 * from element attributes. The single source of truth shared by the server, the
 * dashboard SPA, the interactive DOM snapshot picker (which runs in the
 * browser), and the Playwright reporter (which bundles this at build time).
 */
import type {
  RankedLocator,
  ElementAttributes,
  SelectorCounts,
  RolePosition,
  AncestorAnchor,
} from './locator-healing-types';

export type { RankedLocator, ElementAttributes, SelectorCounts, RolePosition, AncestorAnchor };

// ── ARIA role resolution ─────────────────────────────────────────────────────

/** Implicit ARIA role for an HTML tag (when no explicit `role` is set). */
export const TAG_TO_ROLE: Record<string, string> = {
  a: 'link',
  button: 'button',
  nav: 'navigation',
  main: 'main',
  article: 'article',
  section: 'region',
  form: 'form',
  img: 'img',
  figure: 'figure',
  figcaption: 'caption',
  blockquote: 'blockquote',
  table: 'table',
  ul: 'list',
  ol: 'list',
  li: 'listitem',
  dialog: 'dialog',
  output: 'status',
  progress: 'progressbar',
  meter: 'meter',
  textarea: 'textbox',
  h1: 'heading',
  h2: 'heading',
  h3: 'heading',
  h4: 'heading',
  h5: 'heading',
  h6: 'heading',
  details: 'group',
  summary: 'button',
  search: 'search',
};

/** Implicit ARIA role for an `<input>` keyed by its `type` attribute. */
export const INPUT_TYPE_TO_ROLE: Record<string, string> = {
  button: 'button',
  submit: 'button',
  reset: 'button',
  image: 'button',
  checkbox: 'checkbox',
  radio: 'radio',
  range: 'slider',
  search: 'searchbox',
  number: 'spinbutton',
  text: 'textbox',
  email: 'textbox',
  tel: 'textbox',
  url: 'textbox',
  password: 'textbox',
};

/** Element attributes captured by the probe. */
export const CAPTURED_ATTRIBUTES: string[] = [
  'id',
  'class',
  'name',
  'data-testid',
  'placeholder',
  'alt',
  'title',
  'aria-label',
  'aria-level',
  'role',
  'type',
  'href',
  'multiple',
];

export function resolveAriaRole(attrs: ElementAttributes): string | null {
  const explicit = attrs.attributes['role'];
  if (explicit) return explicit;

  const tag = attrs.tagName;
  if (!tag) return null;

  if (tag === 'input') {
    const type = (attrs.attributes['type'] ?? 'text').toLowerCase();
    return INPUT_TYPE_TO_ROLE[type] ?? 'textbox';
  }

  if (tag === 'select') {
    return attrs.attributes['multiple'] != null ? 'listbox' : 'combobox';
  }

  if (tag === 'a') {
    return attrs.attributes['href'] != null ? 'link' : null;
  }

  return TAG_TO_ROLE[tag] ?? null;
}

export function headingLevel(attrs: ElementAttributes, role: string | null): number | null {
  if (role !== 'heading') return null;
  const tagMatch = attrs.tagName.match(/^h([1-6])$/);
  if (tagMatch) return Number(tagMatch[1]);
  const ariaLevel = attrs.attributes['aria-level'];
  if (ariaLevel && /^\d+$/.test(ariaLevel)) return Number(ariaLevel);
  return null;
}

// ── String utilities ────────────────────────────────────────────────────────

const attr = (a: ElementAttributes, key: string): string | null => a.attributes[key] || null;
const esc = (s: string): string => s.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
const escCssAttrValue = (s: string): string => s.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
const isCssSafeId = (id: string): boolean => /^[A-Za-z][A-Za-z0-9_-]*$/.test(id);

// ── CSS class stability ──────────────────────────────────────────────────────

export function classifyCssStability(className: string): number {
  if (/[a-f0-9]{8,}/i.test(className)) return 10;
  if (/^(?:css|sc|emotion|styled)-/i.test(className)) return 15;
  if (
    /^(bg|text|border|shadow|opacity|font|w-|h-|m[tblrxy]?-|p[tblrxy]?-|flex|grid|gap|rounded|absolute|relative|fixed|sticky|block|inline|hidden|overflow|z-|top-|right-|bottom-|left-|inset-|justify-|items-|self-|content-|order-|col-|row-)/.test(
      className,
    )
  )
    return 25;
  if (/__/.test(className) || /--/.test(className)) return 35;
  if (/^[a-z]+(-[a-z]+)+$/.test(className)) return 40;
  if (/^[a-z]+[A-Z][a-zA-Z]+$/.test(className)) return 40;
  if (className.includes('_')) return 15;
  if (/^[a-z]+-[a-z0-9]{5,}$/.test(className) && /[0-9]/.test(className)) return 15;
  return 15;
}

// ── Auto-generation detection ────────────────────────────────────────────────

export function isAutoGenerated(value: string): boolean {
  if (/^[a-f0-9]{8}-([a-f0-9]{4}-){3}[a-f0-9]{12}$/i.test(value)) return true;
  if (/^[a-f0-9]{8,}$/i.test(value)) return true;
  if (/^[a-z]+-\d+$/.test(value)) return true;
  if (/^(emotion-|styled-|css-|sc-)/.test(value)) return true;
  if (value.startsWith('ng-')) return true;
  if (/^(radix-|headlessui-|mui-|mantine-|chakra-)/i.test(value)) return true;
  if (/^:r[0-9a-z]+:$/i.test(value) || /^«r[0-9a-z]+»$/i.test(value)) return true;
  return false;
}

// ── Alternative generation ───────────────────────────────────────────────────

export function generateAlternatives(attrs: ElementAttributes): RankedLocator[] {
  const alts: RankedLocator[] = [];
  const seen = new Set<string>();
  const add = (loc: RankedLocator) => {
    if (!seen.has(loc.locator)) {
      seen.add(loc.locator);
      alts.push(loc);
    }
  };

  const { accessibleName } = attrs;
  const tag = attrs.tagName;
  const role = resolveAriaRole(attrs);
  const counts = attrs.selectorCounts as SelectorCounts | undefined;
  const isUnique = (n: number | undefined): boolean => n == null || n <= 1;
  const text = attrs.textContent ? attrs.textContent.replace(/\s+/g, ' ').trim() : null;

  // 1. data-testid
  const testId = attr(attrs, 'data-testid');
  if (testId && isUnique(counts?.testId)) {
    add({
      locator: `getByTestId('${esc(testId)}')`,
      method: 'getByTestId',
      args: { testId },
      score: 100,
    });
  }

  const level = headingLevel(attrs, role);
  const levelPart = level != null ? `, level: ${level}` : '';
  const withLevel = (base: Record<string, unknown>): Record<string, unknown> =>
    level != null ? { ...base, level } : base;

  // 2. role + accessible name
  if (role && accessibleName) {
    add({
      locator: `getByRole('${role}', { name: '${esc(accessibleName)}'${levelPart} })`,
      method: 'getByRole',
      args: withLevel({ role, name: accessibleName }),
      score: 90,
    });
  }

  // 3. role + explicit aria-label
  const ariaLabel = attr(attrs, 'aria-label');
  if (role && ariaLabel && ariaLabel !== accessibleName) {
    add({
      locator: `getByRole('${role}', { name: '${esc(ariaLabel)}'${levelPart} })`,
      method: 'getByRole',
      args: withLevel({ role, name: ariaLabel }),
      score: 85,
    });
  }

  // 4. getByLabel
  if (accessibleName && ['input', 'select', 'textarea'].includes(tag)) {
    const label = attr(attrs, 'aria-label');
    const labelBacked = attrs.hasLabel === undefined ? true : attrs.hasLabel === true || label === accessibleName;
    if (labelBacked) {
      add({
        locator: `getByLabel('${esc(accessibleName)}')`,
        method: 'getByLabel',
        args: { label: accessibleName },
        score: 85,
      });
    }
  }

  // 5. getByPlaceholder
  const placeholder = attr(attrs, 'placeholder');
  if (placeholder) {
    add({
      locator: `getByPlaceholder('${esc(placeholder)}')`,
      method: 'getByPlaceholder',
      args: { placeholder },
      score: 80,
    });
  }

  // 6. getByText
  if (text && text.length < 80) {
    add({
      locator: `getByText('${esc(text)}')`,
      method: 'getByText',
      args: { text },
      score: 75,
    });
  }

  // 7. locator('#id')
  const id = attr(attrs, 'id');
  if (id && !isAutoGenerated(id) && isUnique(counts?.id)) {
    const selector = isCssSafeId(id) ? `#${id}` : `[id="${escCssAttrValue(id)}"]`;
    add({
      locator: `locator('${esc(selector)}')`,
      method: 'locator',
      args: { selector },
      score: 65,
    });
  }

  // 8. locator('[name="..."]')
  const name = attr(attrs, 'name');
  if (name && isUnique(counts?.name)) {
    const selector = `[name="${escCssAttrValue(name)}"]`;
    add({
      locator: `locator('${esc(selector)}')`,
      method: 'locator',
      args: { selector },
      score: 60,
    });
  }

  // 9. getByAltText
  const alt = attr(attrs, 'alt');
  if (alt) {
    add({
      locator: `getByAltText('${esc(alt)}')`,
      method: 'getByAltText',
      args: { text: alt },
      score: 60,
    });
  }

  // 10. getByTitle
  const title = attr(attrs, 'title');
  if (title) {
    add({
      locator: `getByTitle('${esc(title)}')`,
      method: 'getByTitle',
      args: { title },
      score: 50,
    });
  }

  // Structural alternatives — name-free, survive renames
  const hasOwnTestId = !!(testId && isUnique(counts?.testId));
  if (role && !hasOwnTestId) {
    const rolePart = level != null ? `'${role}', { level: ${level} }` : `'${role}'`;
    const leafArgs = withLevel({ role });

    let testIdAnchorDone = false;
    let idAnchorDone = false;
    let roleAnchorDone = false;
    for (const anc of attrs.ancestors ?? []) {
      if (anc.scopedRoleCount !== 1) continue;

      if (!testIdAnchorDone && anc.testId && anc.testIdCount === 1) {
        testIdAnchorDone = true;
        add({
          locator: `getByTestId('${esc(anc.testId)}').getByRole(${rolePart})`,
          method: 'getByRole',
          args: { ...leafArgs, anchorTestId: anc.testId },
          score: 72,
        });
      }

      if (!idAnchorDone && anc.id && !isAutoGenerated(anc.id) && anc.idCount === 1) {
        idAnchorDone = true;
        const anchorSelector = isCssSafeId(anc.id) ? `#${anc.id}` : `[id="${escCssAttrValue(anc.id)}"]`;
        add({
          locator: `locator('${esc(anchorSelector)}').getByRole(${rolePart})`,
          method: 'getByRole',
          args: { ...leafArgs, anchorSelector },
          score: 64,
        });
      }

      const ancestorRole = anc.role || TAG_TO_ROLE[anc.tag] || null;
      if (!roleAnchorDone && ancestorRole && ancestorRole !== role && anc.roleCount === 1) {
        roleAnchorDone = true;
        add({
          locator: `getByRole('${esc(ancestorRole)}').getByRole(${rolePart})`,
          method: 'getByRole',
          args: { ...leafArgs, anchorRole: ancestorRole },
          score: 55,
        });
      }
    }

    // Name-free bare role
    const pos = attrs.rolePosition as RolePosition | undefined;
    if (pos && pos.role === role && (pos.count === 1 || (level != null && pos.levelCount === 1))) {
      add({
        locator: `getByRole(${rolePart})`,
        method: 'getByRole',
        args: leafArgs,
        score: 58,
      });
    }
  }

  // CSS class-based
  const clsStr = attr(attrs, 'class');
  if (clsStr) {
    const countsClasses = counts?.classes as Record<string, number> | undefined;
    const classes = clsStr
      .split(/\s+/)
      .filter((c) => c.length > 1 && /^[A-Za-z_-][A-Za-z0-9_-]*$/.test(c) && isUnique(countsClasses?.[c]))
      .map((cls) => ({ cls, score: classifyCssStability(cls) }))
      .sort((a, b) => b.score - a.score)
      .slice(0, 3);

    for (const { cls, score } of classes) {
      add({
        locator: `locator('.${esc(cls)}')`,
        method: 'locator',
        args: { selector: `.${cls}` },
        score,
      });
    }
  }

  return alts.sort((a, b) => b.score - a.score);
}

// ── Accessible name ──────────────────────────────────────────────────────────

export function approximateAccessibleName(attrs: ElementAttributes): string | null {
  const a = attrs.attributes;
  const ariaLabel = a['aria-label'];
  if (ariaLabel) return ariaLabel;
  if (attrs.textContent) return attrs.textContent;
  const title = a['title'];
  if (title) return title;
  const placeholder = a['placeholder'];
  if (placeholder) return placeholder;
  return null;
}
