import { isAutoGenerated } from '@piwitests/core/locator-generation';
import type { RankedLocator } from '@piwitests/core/locator-healing-types';
import type { PickedAnchorInfo, PickedLeafInfo } from './overlay-anchors.js';

const escStr = (s: string): string => s.replaceAll('\\', '\\\\').replaceAll("'", "\\'");
const cssIdSelector = (id: string): string =>
  /^[A-Za-z_][A-Za-z0-9_-]*$/.test(id) ? `#${id}` : `[id="${id.replaceAll('\\', '\\\\').replaceAll('"', '\\"')}"]`;

/**
 * Per-hook-kind stability score for a user-blessed anchor segment. Sits above
 * the heuristic chain scores (55–72 in `generateAlternatives`) because a
 * person vouched for the anchor.
 */
export const ANCHOR_KIND_SCORES = { testid: 80, id: 74, labeledRole: 68, role: 62 } as const;
type AnchorKind = keyof typeof ANCHOR_KIND_SCORES;

/** The strongest document-unique hook an anchor offers, rendered as a chain segment. */
function anchorSegment(
  a: PickedAnchorInfo,
): { code: string; kind: AnchorKind; flatArgs: Record<string, unknown> } | null {
  if (a.testId && a.testIdCount === 1) {
    return { code: `getByTestId('${escStr(a.testId)}')`, kind: 'testid', flatArgs: { anchorTestId: a.testId } };
  }
  if (a.id && !isAutoGenerated(a.id) && a.idCount === 1) {
    const anchorSelector = cssIdSelector(a.id);
    return { code: `locator('${escStr(anchorSelector)}')`, kind: 'id', flatArgs: { anchorSelector } };
  }
  // The anchor's aria-label rides under `anchorName` — never `name`, which the
  // server's fingerprint reader reserves for the LEAF element's accessible name.
  if (a.role && a.ariaLabel && a.labeledRoleCount === 1) {
    return {
      code: `getByRole('${escStr(a.role)}', { name: '${escStr(a.ariaLabel)}' })`,
      kind: 'labeledRole',
      flatArgs: { anchorRole: a.role, anchorName: a.ariaLabel },
    };
  }
  if (a.role && a.roleCount === 1) {
    return { code: `getByRole('${escStr(a.role)}')`, kind: 'role', flatArgs: { anchorRole: a.role } };
  }
  return null;
}

/**
 * Build anchor-scoped candidates from the human-blessed parents. Shapes stay
 * consistent with the heuristic chains in `generateAlternatives` — leaf method
 * `getByRole` with flat anchor args, no leaf `name` key. Single-anchor
 * candidates require the leaf to be unique inside that anchor; with two or
 * more anchors a combined chain is added when the whole chain resolves to
 * exactly one element (`chainLeafCount`). Pure — exported for tests.
 */
export function generateAnchoredAlternatives(
  leaf: PickedLeafInfo,
  anchors: PickedAnchorInfo[],
  chainLeafCount?: number,
): RankedLocator[] {
  if (!leaf.role || anchors.length === 0) return [];
  const out: RankedLocator[] = [];
  const seen = new Set<string>();
  const rolePart = leaf.level != null ? `'${leaf.role}', { level: ${leaf.level} }` : `'${leaf.role}'`;
  const leafArgs: Record<string, unknown> =
    leaf.level != null ? { role: leaf.role, level: leaf.level } : { role: leaf.role };
  const add = (l: RankedLocator) => {
    if (!seen.has(l.locator)) {
      seen.add(l.locator);
      out.push(l);
    }
  };

  for (const anchor of anchors) {
    if (anchor.scopedLeafCount !== 1) continue;
    const seg = anchorSegment(anchor);
    if (!seg) continue;
    add({
      locator: `${seg.code}.getByRole(${rolePart})`,
      method: 'getByRole',
      args: { ...leafArgs, ...seg.flatArgs },
      score: ANCHOR_KIND_SCORES[seg.kind],
    });
  }

  // Combined chain, outermost anchor first — only when the human picked
  // several parents and the whole chain isolates exactly one element.
  if (anchors.length >= 2 && chainLeafCount === 1) {
    const ordered = [...anchors].sort((a, b) => b.depth - a.depth);
    const segments = ordered.map(anchorSegment);
    if (segments.every((s) => s !== null)) {
      const innermost = segments[segments.length - 1]!;
      // A chain is as sturdy as its weakest segment.
      const score = Math.min(...segments.map((s) => ANCHOR_KIND_SCORES[s!.kind]));
      add({
        locator: `${segments.map((s) => s!.code).join('.')}.getByRole(${rolePart})`,
        method: 'getByRole',
        // Flat args describe the innermost anchor (what the healing fingerprint
        // logic understands); the full chain rides along for transparency.
        args: { ...leafArgs, ...innermost.flatArgs, anchorChain: segments.map((s) => s!.code) },
        score,
      });
    }
  }

  return out.sort((a, b) => b.score - a.score);
}

/** Merge candidate lists, first list winning duplicates, sorted by score. Exported for tests. */
export function mergeCandidates(base: RankedLocator[], extra: RankedLocator[]): RankedLocator[] {
  const seen = new Set(base.map((b) => b.locator));
  const merged = [...base];
  for (const e of extra) {
    if (seen.has(e.locator)) continue;
    seen.add(e.locator);
    merged.push(e);
  }
  return merged.sort((a, b) => b.score - a.score);
}
