import { describe, it, expect } from 'vitest';
import {
  captureCallerLocation,
  generateAlternatives,
  classifyCssStability,
  dedupeSnapshotsByLocation,
  isAutoGenerated,
  extractAccessibleName,
  approximateAccessibleName,
  resolveAriaRole,
  suggestLocatorsFromAria,
  CAPTURED_ATTRIBUTES,
  EXPECT_CAPTURE_EXPRESSIONS,
  EXPECT_METHOD,
  type AncestorAnchor,
  type ElementAttributes,
  type LocatorSnapshot,
} from '../src/internal/capture/locator-healing.js';

function makeAttrs(overrides: Partial<ElementAttributes & { attrs: Record<string, string | null> }> = {}) {
  const a = overrides.attrs ?? {};
  return {
    tagName: overrides.tagName ?? 'button',
    attributes: {
      id: a.id ?? null,
      class: a.class ?? null,
      name: a.name ?? null,
      'data-testid': a['data-testid'] ?? null,
      placeholder: a.placeholder ?? null,
      alt: a.alt ?? null,
      title: a.title ?? null,
      'aria-label': a['aria-label'] ?? null,
      'aria-level': a['aria-level'] ?? null,
      role: a.role ?? null,
      type: a.type ?? null,
      href: a.href ?? null,
      multiple: a.multiple ?? null,
    },
    textContent: overrides.textContent ?? null,
    accessibleName: overrides.accessibleName ?? null,
    center: overrides.center ?? null,
    ...(overrides.hasLabel !== undefined ? { hasLabel: overrides.hasLabel } : {}),
    ...(overrides.selectorCounts !== undefined ? { selectorCounts: overrides.selectorCounts } : {}),
    ...(overrides.rolePosition !== undefined ? { rolePosition: overrides.rolePosition } : {}),
    ...(overrides.ancestors !== undefined ? { ancestors: overrides.ancestors } : {}),
  };
}

/** An anchor-worthy ancestor with sensible defaults for the structural tests. */
function makeAnchor(overrides: Partial<AncestorAnchor> = {}) {
  return {
    tag: 'form',
    depth: 1,
    testId: null,
    id: null,
    role: null,
    ariaLabel: null,
    scopedRoleCount: 1,
    ...overrides,
  };
}

describe('generateAlternatives', () => {
  it('ranks data-testid highest (100)', () => {
    const attrs = makeAttrs({ attrs: { 'data-testid': 'submit-btn' } });
    const alts = generateAlternatives(attrs);
    expect(alts.length).toBeGreaterThan(0);
    expect(alts[0]!.method).toBe('getByTestId');
    expect(alts[0]!.score).toBe(100);
    expect(alts[0]!.locator).toBe("getByTestId('submit-btn')");
  });

  it('generates role + accessible name (90)', () => {
    const attrs = makeAttrs({ tagName: 'button', accessibleName: 'Submit order' });
    const alts = generateAlternatives(attrs);
    const roleAlt = alts.find((a) => a.method === 'getByRole' && a.score === 90);
    expect(roleAlt).toBeTruthy();
    expect(roleAlt!.locator).toContain("name: 'Submit order'");
  });

  it('generates role + aria-label when different from accessible name', () => {
    const attrs = makeAttrs({
      tagName: 'button',
      accessibleName: 'Submit order',
      attrs: { 'aria-label': 'Submit' },
    });
    const alts = generateAlternatives(attrs);
    const ariaAlt = alts.find((a) => a.method === 'getByRole' && a.score === 85);
    expect(ariaAlt).toBeTruthy();
  });

  it('skips role + aria-label when it equals accessible name', () => {
    const attrs = makeAttrs({
      tagName: 'button',
      accessibleName: 'Submit',
      attrs: { 'aria-label': 'Submit' },
    });
    const alts = generateAlternatives(attrs);
    // Should have role+accessibleName (90) but not a duplicate role+aria-label (85)
    const roleAlts = alts.filter((a) => a.method === 'getByRole');
    expect(roleAlts.length).toBe(1);
  });

  it('maps <input> to the textbox role, not the tag name', () => {
    const attrs = makeAttrs({ tagName: 'input', accessibleName: 'Email' });
    const alts = generateAlternatives(attrs);
    const roleAlt = alts.find((a) => a.method === 'getByRole' && a.score === 90);
    expect(roleAlt).toBeTruthy();
    expect(roleAlt!.locator).toBe("getByRole('textbox', { name: 'Email' })");
    expect(roleAlt!.args).toEqual({ role: 'textbox', name: 'Email' });
  });

  it('maps <input type=checkbox> to the checkbox role', () => {
    const attrs = makeAttrs({ tagName: 'input', attrs: { type: 'checkbox' }, accessibleName: 'Remember me' });
    const alts = generateAlternatives(attrs);
    const roleAlt = alts.find((a) => a.method === 'getByRole' && a.score === 90);
    expect(roleAlt).toBeTruthy();
    expect(roleAlt!.args.role).toBe('checkbox');
  });

  it('maps a plain <select> to the combobox role, <select multiple> to listbox', () => {
    const attrs = makeAttrs({ tagName: 'select', accessibleName: 'Country' });
    const alts = generateAlternatives(attrs);
    const roleAlt = alts.find((a) => a.method === 'getByRole' && a.score === 90);
    expect(roleAlt).toBeTruthy();
    expect(roleAlt!.args.role).toBe('combobox');

    const multi = makeAttrs({ tagName: 'select', accessibleName: 'Tags', attrs: { multiple: '' } });
    const multiAlt = generateAlternatives(multi).find((a) => a.method === 'getByRole' && a.score === 90);
    expect(multiAlt).toBeTruthy();
    expect(multiAlt!.args.role).toBe('listbox');
  });

  it('maps <textarea> to the textbox role', () => {
    const attrs = makeAttrs({ tagName: 'textarea', accessibleName: 'Comment' });
    const alts = generateAlternatives(attrs);
    const roleAlt = alts.find((a) => a.method === 'getByRole' && a.score === 90);
    expect(roleAlt).toBeTruthy();
    expect(roleAlt!.args.role).toBe('textbox');
  });

  it('maps <a href> to the link role', () => {
    const attrs = makeAttrs({ tagName: 'a', attrs: { href: '/home' }, accessibleName: 'Home' });
    const alts = generateAlternatives(attrs);
    const roleAlt = alts.find((a) => a.method === 'getByRole' && a.score === 90);
    expect(roleAlt).toBeTruthy();
    expect(roleAlt!.args.role).toBe('link');
  });

  it('maps <nav> to the navigation role', () => {
    const attrs = makeAttrs({ tagName: 'nav', accessibleName: 'Main' });
    const alts = generateAlternatives(attrs);
    const roleAlt = alts.find((a) => a.method === 'getByRole' && a.score === 90);
    expect(roleAlt).toBeTruthy();
    expect(roleAlt!.args.role).toBe('navigation');
  });

  it('maps <h1> to the heading role', () => {
    const attrs = makeAttrs({ tagName: 'h1', accessibleName: 'Welcome' });
    const alts = generateAlternatives(attrs);
    const roleAlt = alts.find((a) => a.method === 'getByRole' && a.score === 90);
    expect(roleAlt).toBeTruthy();
    expect(roleAlt!.args.role).toBe('heading');
  });

  it('does not generate getByRole for <div> (no implicit role)', () => {
    const attrs = makeAttrs({ tagName: 'div', accessibleName: 'Hello' });
    const alts = generateAlternatives(attrs);
    const roleAlt = alts.find((a) => a.method === 'getByRole');
    expect(roleAlt).toBeUndefined();
  });

  it('does not generate getByRole for <a> without href', () => {
    const attrs = makeAttrs({ tagName: 'a', accessibleName: 'Home' });
    const alts = generateAlternatives(attrs);
    const roleAlt = alts.find((a) => a.method === 'getByRole');
    expect(roleAlt).toBeUndefined();
  });

  it('prefers an explicit role attribute over the implicit tag role', () => {
    const attrs = makeAttrs({ tagName: 'div', attrs: { role: 'button' }, accessibleName: 'Submit' });
    const alts = generateAlternatives(attrs);
    const roleAlt = alts.find((a) => a.method === 'getByRole' && a.score === 90);
    expect(roleAlt).toBeTruthy();
    expect(roleAlt!.args.role).toBe('button');
  });

  it('generates getByLabel for form fields', () => {
    const attrs = makeAttrs({ tagName: 'input', accessibleName: 'Email' });
    const alts = generateAlternatives(attrs);
    const labelAlt = alts.find((a) => a.method === 'getByLabel');
    expect(labelAlt).toBeTruthy();
    expect(labelAlt!.score).toBe(85);
  });

  it('does not generate getByLabel for non-form elements', () => {
    const attrs = makeAttrs({ tagName: 'div', accessibleName: 'Hello' });
    const alts = generateAlternatives(attrs);
    const labelAlt = alts.find((a) => a.method === 'getByLabel');
    expect(labelAlt).toBeUndefined();
  });

  it('generates getByPlaceholder (80)', () => {
    const attrs = makeAttrs({ attrs: { placeholder: 'Enter your name' } });
    const alts = generateAlternatives(attrs);
    const placeholderAlt = alts.find((a) => a.method === 'getByPlaceholder');
    expect(placeholderAlt).toBeTruthy();
    expect(placeholderAlt!.score).toBe(80);
  });

  it('generates getByText for short text (75)', () => {
    const attrs = makeAttrs({ textContent: 'Click me' });
    const alts = generateAlternatives(attrs);
    const textAlt = alts.find((a) => a.method === 'getByText');
    expect(textAlt).toBeTruthy();
    expect(textAlt!.score).toBe(75);
  });

  it('skips getByText for long text (>80 chars)', () => {
    const attrs = makeAttrs({ textContent: 'a'.repeat(81) });
    const alts = generateAlternatives(attrs);
    const textAlt = alts.find((a) => a.method === 'getByText');
    expect(textAlt).toBeUndefined();
  });

  it('generates locator(#id) for stable ids (65)', () => {
    const attrs = makeAttrs({ attrs: { id: 'login-form' } });
    const alts = generateAlternatives(attrs);
    const idAlt = alts.find((a) => a.method === 'locator' && a.locator.startsWith("locator('#"));
    expect(idAlt).toBeTruthy();
    expect(idAlt!.score).toBe(65);
  });

  it('skips locator(#id) for auto-generated ids', () => {
    const attrs = makeAttrs({ attrs: { id: 'emotion-abc123def456' } });
    const alts = generateAlternatives(attrs);
    const idAlt = alts.find((a) => a.method === 'locator' && a.locator.startsWith("locator('#"));
    expect(idAlt).toBeUndefined();
  });

  it('generates locator([name="..."]) (60)', () => {
    const attrs = makeAttrs({ attrs: { name: 'username' } });
    const alts = generateAlternatives(attrs);
    const nameAlt = alts.find((a) => a.method === 'locator' && a.locator.includes('[name='));
    expect(nameAlt).toBeTruthy();
    expect(nameAlt!.score).toBe(60);
  });

  it('generates getByAltText (60)', () => {
    const attrs = makeAttrs({ attrs: { alt: 'Product photo' } });
    const alts = generateAlternatives(attrs);
    const altTextAlt = alts.find((a) => a.method === 'getByAltText');
    expect(altTextAlt).toBeTruthy();
    expect(altTextAlt!.score).toBe(60);
  });

  it('generates getByTitle (50)', () => {
    const attrs = makeAttrs({ attrs: { title: 'More info' } });
    const alts = generateAlternatives(attrs);
    const titleAlt = alts.find((a) => a.method === 'getByTitle');
    expect(titleAlt).toBeTruthy();
    expect(titleAlt!.score).toBe(50);
  });

  it('generates CSS class alternatives capped at 3', () => {
    const attrs = makeAttrs({ attrs: { class: 'a b c d e f' } });
    const alts = generateAlternatives(attrs);
    const cssAlts = alts.filter((a) => a.method === 'locator' && a.locator.startsWith("locator('."));
    expect(cssAlts.length).toBeLessThanOrEqual(3);
  });

  it('sorts alternatives by score descending', () => {
    const attrs = makeAttrs({
      tagName: 'button',
      accessibleName: 'Submit',
      attrs: {
        'data-testid': 'submit-btn',
        class: 'btn-primary',
        id: 'submit',
      },
    });
    const alts = generateAlternatives(attrs);
    for (let i = 1; i < alts.length; i++) {
      expect(alts[i]!.score).toBeLessThanOrEqual(alts[i - 1]!.score);
    }
  });

  it('does not generate duplicate locator expressions', () => {
    const attrs = makeAttrs({
      tagName: 'button',
      accessibleName: 'Click',
      textContent: 'Click',
    });
    const alts = generateAlternatives(attrs);
    const locators = alts.map((a) => a.locator);
    expect(new Set(locators).size).toBe(locators.length);
  });

  it('returns empty array for minimal attributes', () => {
    const attrs = makeAttrs();
    const alts = generateAlternatives(attrs);
    expect(alts.length).toBe(0);
  });

  it('escapes single quotes in locator expressions', () => {
    const attrs = makeAttrs({ attrs: { 'data-testid': "it's-working" } });
    const alts = generateAlternatives(attrs);
    expect(alts[0]!.locator).toBe("getByTestId('it\\'s-working')");
  });

  it('does not capture the live input value (secret-leak guard)', () => {
    expect(CAPTURED_ATTRIBUTES).not.toContain('value');
  });

  it('collapses whitespace in getByText suggestions', () => {
    const attrs = makeAttrs({ textContent: 'Line one\n   Line two' });
    const alts = generateAlternatives(attrs);
    const textAlt = alts.find((a) => a.method === 'getByText');
    expect(textAlt).toBeTruthy();
    expect(textAlt!.locator).toBe("getByText('Line one Line two')");
  });

  it('suppresses getByLabel when the probe says there is no label backing the name', () => {
    // Accessible name approximated from the placeholder — getByLabel would match nothing.
    const attrs = makeAttrs({
      tagName: 'input',
      accessibleName: 'Search',
      attrs: { placeholder: 'Search' },
      hasLabel: false,
    });
    const alts = generateAlternatives(attrs);
    expect(alts.find((a) => a.method === 'getByLabel')).toBeUndefined();
    expect(alts.find((a) => a.method === 'getByPlaceholder')).toBeTruthy();
  });

  it('keeps getByLabel when a real <label> or matching aria-label exists', () => {
    const labelled = makeAttrs({ tagName: 'input', accessibleName: 'Email', hasLabel: true });
    expect(generateAlternatives(labelled).find((a) => a.method === 'getByLabel')).toBeTruthy();

    const ariaLabelled = makeAttrs({
      tagName: 'input',
      accessibleName: 'Email',
      attrs: { 'aria-label': 'Email' },
      hasLabel: false,
    });
    expect(generateAlternatives(ariaLabelled).find((a) => a.method === 'getByLabel')).toBeTruthy();
  });

  it('uses an attribute selector for ids that are not CSS-safe', () => {
    const attrs = makeAttrs({ attrs: { id: 'user.profile' } });
    const alts = generateAlternatives(attrs);
    const idAlt = alts.find((a) => a.method === 'locator' && a.locator.includes('[id='));
    expect(idAlt).toBeTruthy();
    expect(idAlt!.args.selector).toBe('[id="user.profile"]');
  });

  it('drops alternatives whose probed selector count is ambiguous (>1)', () => {
    const attrs = makeAttrs({
      attrs: { 'data-testid': 'row-action', id: 'dup', name: 'q', class: 'btn card-title' },
      selectorCounts: { testId: 3, id: 2, name: 2, classes: { btn: 12, 'card-title': 1 } },
    });
    const alts = generateAlternatives(attrs);
    expect(alts.find((a) => a.method === 'getByTestId')).toBeUndefined();
    expect(alts.find((a) => a.locator.includes('#dup'))).toBeUndefined();
    expect(alts.find((a) => a.locator.includes('[name='))).toBeUndefined();
    expect(alts.find((a) => a.locator.includes('.btn'))).toBeUndefined();
    expect(alts.find((a) => a.locator.includes('.card-title'))).toBeTruthy();
  });

  it('keeps alternatives when no uniqueness probe data is present', () => {
    const attrs = makeAttrs({ attrs: { 'data-testid': 'row-action' } });
    expect(generateAlternatives(attrs).find((a) => a.method === 'getByTestId')).toBeTruthy();
  });

  it('skips CSS classes that are not valid bare selectors (Tailwind variants)', () => {
    const attrs = makeAttrs({ attrs: { class: 'hover:bg-red-500 w-[10px] card-title' } });
    const alts = generateAlternatives(attrs);
    const cssAlts = alts.filter((a) => a.method === 'locator' && a.locator.startsWith("locator('."));
    expect(cssAlts.map((a) => a.locator)).toEqual(["locator('.card-title')"]);
  });
});

describe('generateAlternatives — structural (rename-proof) alternatives', () => {
  it('emits a heading getByRole with its level in name-derived alternatives', () => {
    const attrs = makeAttrs({ tagName: 'h1', accessibleName: 'Dashboard' });
    const roleAlt = generateAlternatives(attrs).find((a) => a.method === 'getByRole' && a.score === 90);
    expect(roleAlt!.locator).toBe("getByRole('heading', { name: 'Dashboard', level: 1 })");
    expect(roleAlt!.args).toEqual({ role: 'heading', name: 'Dashboard', level: 1 });
  });

  it('reads the heading level from aria-level for explicit role="heading"', () => {
    const attrs = makeAttrs({ tagName: 'div', attrs: { role: 'heading', 'aria-level': '3' }, accessibleName: 'Hi' });
    const roleAlt = generateAlternatives(attrs).find((a) => a.method === 'getByRole' && a.score === 90);
    expect(roleAlt!.args).toEqual({ role: 'heading', name: 'Hi', level: 3 });
  });

  it('anchors to a data-testid ancestor when the leaf role is unique inside it (72)', () => {
    const attrs = makeAttrs({
      tagName: 'input',
      attrs: { type: 'email' },
      accessibleName: 'Email',
      hasLabel: true,
      ancestors: [makeAnchor({ testId: 'signup-form', testIdCount: 1 })],
    });
    const alt = generateAlternatives(attrs).find((a) => a.score === 72);
    expect(alt!.locator).toBe("getByTestId('signup-form').getByRole('textbox')");
    expect(alt!.method).toBe('getByRole');
    expect(alt!.args).toEqual({ role: 'textbox', anchorTestId: 'signup-form' });
  });

  it('anchors to an id ancestor (64) and a unique landmark ancestor (55)', () => {
    const attrs = makeAttrs({
      tagName: 'a',
      attrs: { href: '/docs' },
      accessibleName: 'Docs',
      ancestors: [
        makeAnchor({ tag: 'div', id: 'sidebar', idCount: 1 }),
        makeAnchor({ tag: 'nav', depth: 2, roleCount: 1 }),
      ],
    });
    const alts = generateAlternatives(attrs);
    const idAlt = alts.find((a) => a.score === 64);
    expect(idAlt!.locator).toBe("locator('#sidebar').getByRole('link')");
    expect(idAlt!.args).toEqual({ role: 'link', anchorSelector: '#sidebar' });
    const roleAlt = alts.find((a) => a.score === 55);
    expect(roleAlt!.locator).toBe("getByRole('navigation').getByRole('link')");
    expect(roleAlt!.args).toEqual({ role: 'link', anchorRole: 'navigation' });
  });

  it('anchors to an app-specific data-* ancestor (60), and a test-oriented one higher (70)', () => {
    const anchored = (name: string) =>
      generateAlternatives(
        makeAttrs({
          tagName: 'input',
          ancestors: [makeAnchor({ tag: 'div', dataAttr: { name, value: 'row-7' }, dataAttrCount: 1 })],
        }),
      ).find((a) => a.args.anchorSelector);

    const appHook = anchored('data-row-id');
    expect(appHook!.locator).toBe(`locator('[data-row-id="row-7"]').getByRole('textbox')`);
    expect(appHook!.args).toEqual({ role: 'textbox', anchorSelector: '[data-row-id="row-7"]' });
    expect(appHook!.score).toBe(60);

    // data-qa exists to be targeted by tests, so it is trusted like a testid.
    expect(anchored('data-qa')!.score).toBe(70);
  });

  it('scopes a role-less leaf by its text (68/51), one notch under the role chains', () => {
    const attrs = makeAttrs({
      tagName: 'span',
      textContent: '£49.99',
      selectorCounts: { text: 2 },
      ancestors: [
        makeAnchor({ tag: 'div', scopedRoleCount: undefined, scopedTextCount: 1, testId: 'row', testIdCount: 1 }),
        makeAnchor({ tag: 'nav', depth: 3, scopedRoleCount: undefined, scopedTextCount: 1, roleCount: 1 }),
      ],
    });
    const alts = generateAlternatives(attrs);
    expect(alts[0]).toMatchObject({
      locator: "getByTestId('row').getByText('£49.99')",
      method: 'getByText',
      args: { text: '£49.99', anchorTestId: 'row' },
      score: 68,
    });
    expect(alts.find((a) => a.args.anchorRole)).toMatchObject({
      locator: "getByRole('navigation').getByText('£49.99')",
      score: 51,
    });
    // The bare getByText matches both rows, so it drops below both chains.
    expect(alts.find((a) => a.method === 'getByText' && !a.args.anchorTestId && !a.args.anchorRole)!.score).toBe(30);
  });

  it('does not add text chains for a leaf that already has role chains', () => {
    const attrs = makeAttrs({
      tagName: 'button',
      accessibleName: 'Add to cart',
      textContent: 'Add to cart',
      ancestors: [makeAnchor({ tag: 'div', testId: 'row', testIdCount: 1, scopedTextCount: 1 })],
    });
    const alts = generateAlternatives(attrs);
    expect(alts.some((a) => a.method === 'getByText' && a.args.anchorTestId)).toBe(false);
    expect(alts.some((a) => a.method === 'getByRole' && a.args.anchorTestId)).toBe(true);
  });

  it('skips a data-* ancestor whose hook matches several elements', () => {
    const attrs = makeAttrs({
      tagName: 'input',
      ancestors: [makeAnchor({ tag: 'div', dataAttr: { name: 'data-kind', value: 'card' }, dataAttrCount: 6 })],
    });
    expect(generateAlternatives(attrs).some((a) => a.args.anchorSelector)).toBe(false);
  });

  it('takes the nearest qualifying anchor of each kind', () => {
    const attrs = makeAttrs({
      tagName: 'input',
      ancestors: [
        makeAnchor({ testId: 'inner-card', testIdCount: 1 }),
        makeAnchor({ depth: 2, testId: 'outer-card', testIdCount: 1 }),
      ],
    });
    const chains = generateAlternatives(attrs).filter((a) => a.args.anchorTestId);
    expect(chains).toHaveLength(1);
    expect(chains[0]!.args.anchorTestId).toBe('inner-card');
  });

  it('skips anchors that are ambiguous or contain several leaf-role matches', () => {
    const attrs = makeAttrs({
      tagName: 'input',
      ancestors: [
        makeAnchor({ testId: 'dup', testIdCount: 2 }),
        makeAnchor({ depth: 2, testId: 'busy-form', testIdCount: 1, scopedRoleCount: 3 }),
        makeAnchor({ depth: 3, id: 'field-172845', idCount: 1 }),
        makeAnchor({ depth: 4, scopedRoleCount: undefined, testId: 'unprobed', testIdCount: 1 }),
      ],
    });
    // dup: ambiguous testid; busy-form: 3 textboxes inside; field-172845:
    // auto-generated id; unprobed: unknown scoped count — none may chain.
    expect(generateAlternatives(attrs).some((a) => a.args.anchorTestId || a.args.anchorSelector)).toBe(false);
  });

  it('skips all structural alternatives when the element has its own unique testid', () => {
    const attrs = makeAttrs({
      tagName: 'input',
      attrs: { 'data-testid': 'email-input' },
      rolePosition: { role: 'textbox', count: 1, index: 0 },
      ancestors: [makeAnchor({ testId: 'signup-form', testIdCount: 1 })],
    });
    const alts = generateAlternatives(attrs);
    expect(alts.some((a) => a.args.anchorTestId)).toBe(false);
    expect(alts.some((a) => a.method === 'getByRole' && !('name' in a.args))).toBe(false);
  });

  it('emits a name-free getByRole for the sole element of its role (58)', () => {
    const attrs = makeAttrs({
      tagName: 'input',
      attrs: { type: 'search' },
      rolePosition: { role: 'searchbox', count: 1, index: 0 },
    });
    const alt = generateAlternatives(attrs).find((a) => a.score === 58);
    expect(alt!.locator).toBe("getByRole('searchbox')");
    expect(alt!.args).toEqual({ role: 'searchbox' });
  });

  it('emits a level-scoped name-free getByRole for the sole heading at its level', () => {
    const attrs = makeAttrs({
      tagName: 'h1',
      accessibleName: 'Dashboard',
      rolePosition: { role: 'heading', count: 4, index: 0, levelCount: 1 },
    });
    const alt = generateAlternatives(attrs).find((a) => a.score === 58);
    expect(alt!.locator).toBe("getByRole('heading', { level: 1 })");
    expect(alt!.args).toEqual({ role: 'heading', level: 1 });
  });

  it('does not emit a name-free getByRole when the role is ambiguous on the page', () => {
    const attrs = makeAttrs({
      tagName: 'h2',
      accessibleName: 'Stats',
      rolePosition: { role: 'heading', count: 4, index: 2, levelCount: 3 },
    });
    expect(generateAlternatives(attrs).some((a) => a.score === 58)).toBe(false);
  });

  it('structural alternatives sort below name-derived ones', () => {
    const attrs = makeAttrs({
      tagName: 'input',
      accessibleName: 'Email',
      hasLabel: true,
      rolePosition: { role: 'textbox', count: 1, index: 0 },
      ancestors: [makeAnchor({ testId: 'signup-form', testIdCount: 1 })],
    });
    const alts = generateAlternatives(attrs);
    const scores = alts.map((a) => a.score);
    expect(scores).toEqual([...scores].sort((x, y) => y - x));
    expect(alts[0]!.score).toBe(90);
  });
});

describe('dedupeSnapshotsByLocation', () => {
  const snap = (location: string | null, hasElement: boolean): LocatorSnapshot => ({
    location,
    used: { method: 'getByText', args: ['x'], raw: "getByText(['x'])" },
    element: hasElement
      ? { tagName: 'button', attributes: {}, textContent: 'x', accessibleName: 'x', center: null }
      : null,
    alternatives: [],
  });

  it('keeps only the last element-bearing snapshot per location', () => {
    const input = [snap('t.ts:1:1', true), snap('t.ts:1:1', true), snap('t.ts:2:1', true)];
    const out = dedupeSnapshotsByLocation(input);
    expect(out).toEqual([input[1], input[2]]);
  });

  it('falls back to the last placeholder when no capture resolved for a location', () => {
    const input = [snap('t.ts:1:1', false), snap('t.ts:1:1', false)];
    const out = dedupeSnapshotsByLocation(input);
    expect(out).toEqual([input[1]]);
  });

  it('prefers an element-bearing snapshot over a later placeholder (failed retry of a loop)', () => {
    const input = [snap('t.ts:1:1', true), snap('t.ts:1:1', false)];
    const out = dedupeSnapshotsByLocation(input);
    expect(out).toEqual([input[0]]);
  });

  it('passes location-less snapshots through untouched', () => {
    const input = [snap(null, false), snap(null, true)];
    expect(dedupeSnapshotsByLocation(input)).toEqual(input);
  });
});

describe('resolveAriaRole', () => {
  it('returns the explicit role attribute when present', () => {
    expect(resolveAriaRole(makeAttrs({ tagName: 'div', attrs: { role: 'navigation' } }))).toBe('navigation');
  });

  it('maps input to textbox by default', () => {
    expect(resolveAriaRole(makeAttrs({ tagName: 'input' }))).toBe('textbox');
  });

  it('maps input type variants', () => {
    expect(resolveAriaRole(makeAttrs({ tagName: 'input', attrs: { type: 'checkbox' } }))).toBe('checkbox');
    expect(resolveAriaRole(makeAttrs({ tagName: 'input', attrs: { type: 'radio' } }))).toBe('radio');
    expect(resolveAriaRole(makeAttrs({ tagName: 'input', attrs: { type: 'search' } }))).toBe('searchbox');
    expect(resolveAriaRole(makeAttrs({ tagName: 'input', attrs: { type: 'number' } }))).toBe('spinbutton');
    expect(resolveAriaRole(makeAttrs({ tagName: 'input', attrs: { type: 'range' } }))).toBe('slider');
  });

  it('maps structural tags to their implicit roles', () => {
    expect(resolveAriaRole(makeAttrs({ tagName: 'nav' }))).toBe('navigation');
    expect(resolveAriaRole(makeAttrs({ tagName: 'main' }))).toBe('main');
    expect(resolveAriaRole(makeAttrs({ tagName: 'select' }))).toBe('combobox');
    expect(resolveAriaRole(makeAttrs({ tagName: 'select', attrs: { multiple: '' } }))).toBe('listbox');
    expect(resolveAriaRole(makeAttrs({ tagName: 'textarea' }))).toBe('textbox');
    expect(resolveAriaRole(makeAttrs({ tagName: 'h2' }))).toBe('heading');
    expect(resolveAriaRole(makeAttrs({ tagName: 'ul' }))).toBe('list');
    expect(resolveAriaRole(makeAttrs({ tagName: 'form' }))).toBe('form');
  });

  it('maps <a> to link only when href is present', () => {
    expect(resolveAriaRole(makeAttrs({ tagName: 'a', attrs: { href: '/x' } }))).toBe('link');
    expect(resolveAriaRole(makeAttrs({ tagName: 'a' }))).toBeNull();
  });

  it('returns null for tags with no implicit role', () => {
    expect(resolveAriaRole(makeAttrs({ tagName: 'div' }))).toBeNull();
    expect(resolveAriaRole(makeAttrs({ tagName: 'span' }))).toBeNull();
  });
});

describe('classifyCssStability', () => {
  it('scores hash-like suffixes as 10', () => {
    expect(classifyCssStability('btn-abc123')).toBeLessThanOrEqual(15);
    expect(classifyCssStability('xyz_a1b2c3d4')).toBeLessThanOrEqual(15);
  });

  it('scores CSS-in-JS prefixes as 15', () => {
    expect(classifyCssStability('css-xyz')).toBe(15);
    expect(classifyCssStability('sc-bdVaJa')).toBe(15);
    expect(classifyCssStability('emotion-cache')).toBe(15);
    expect(classifyCssStability('styled-button')).toBe(15);
  });

  it('scores utility classes as 25', () => {
    expect(classifyCssStability('bg-red-500')).toBe(25);
    expect(classifyCssStability('flex')).toBe(25);
    expect(classifyCssStability('p-4')).toBe(25);
    expect(classifyCssStability('rounded-lg')).toBe(25);
    expect(classifyCssStability('justify-between')).toBe(25);
  });

  it('scores BEM-style classes as 35', () => {
    expect(classifyCssStability('nav__item')).toBe(35);
    expect(classifyCssStability('btn--active')).toBe(35);
  });

  it('scores plain semantic classes as 40', () => {
    expect(classifyCssStability('submit-button')).toBe(40);
    expect(classifyCssStability('navItem')).toBe(40);
  });
});

describe('isAutoGenerated', () => {
  it('detects UUIDs', () => {
    expect(isAutoGenerated('550e8400-e29b-41d4-a716-446655440000')).toBe(true);
  });

  it('detects hex hashes (8+ chars)', () => {
    expect(isAutoGenerated('abc123def456')).toBe(true);
    expect(isAutoGenerated('feeddeadbeef')).toBe(true);
  });

  it('detects long numeric-suffixed IDs, but keeps short record ids', () => {
    expect(isAutoGenerated('btn-174829')).toBe(true);
    // A short digit suffix is far more often a record id than framework
    // output, and it is the only hook that makes a repeated card addressable.
    expect(isAutoGenerated('btn-42')).toBe(false);
    expect(isAutoGenerated('product-43')).toBe(false);
    expect(isAutoGenerated('row-7')).toBe(false);
  });

  it('detects CSS-in-JS generated IDs', () => {
    expect(isAutoGenerated('emotion-xyz')).toBe(true);
    expect(isAutoGenerated('styled-button')).toBe(true);
    expect(isAutoGenerated('css-1a2b3c')).toBe(true);
  });

  it('detects Angular-style IDs', () => {
    expect(isAutoGenerated('ng-abc123')).toBe(true);
  });

  it('detects component-library and React useId formats', () => {
    expect(isAutoGenerated('radix-:r3:')).toBe(true);
    expect(isAutoGenerated('headlessui-menu-button-1')).toBe(true);
    expect(isAutoGenerated('mui-1234')).toBe(true);
    expect(isAutoGenerated(':r1a:')).toBe(true);
    expect(isAutoGenerated('«r5»')).toBe(true);
  });

  it('allows semantic IDs', () => {
    expect(isAutoGenerated('login-form')).toBe(false);
    expect(isAutoGenerated('submit-button')).toBe(false);
    expect(isAutoGenerated('user-email')).toBe(false);
  });
});

describe('extractAccessibleName', () => {
  it('extracts quoted name from aria snapshot', () => {
    expect(extractAccessibleName('- button "Submit order"')).toBe('Submit order');
    expect(extractAccessibleName('- heading "Welcome, Alice"')).toBe('Welcome, Alice');
    expect(extractAccessibleName('- textbox "Email" [ref=e12]')).toBe('Email');
  });

  it('returns null for elements without a name', () => {
    expect(extractAccessibleName('- generic')).toBe(null);
    expect(extractAccessibleName('- link')).toBe(null);
  });

  it('returns null for null input', () => {
    expect(extractAccessibleName(null)).toBe(null);
  });
});

describe('approximateAccessibleName', () => {
  it('prioritizes aria-label', () => {
    const attrs = makeAttrs({
      attrs: { 'aria-label': 'Close dialog', title: 'Close' },
      textContent: 'X',
    });
    expect(approximateAccessibleName(attrs)).toBe('Close dialog');
  });

  it('falls back to text content', () => {
    const attrs = makeAttrs({ textContent: 'Click here' });
    expect(approximateAccessibleName(attrs)).toBe('Click here');
  });

  it('falls back to title', () => {
    const attrs = makeAttrs({ attrs: { title: 'More info' } });
    expect(approximateAccessibleName(attrs)).toBe('More info');
  });

  it('falls back to placeholder', () => {
    const attrs = makeAttrs({ attrs: { placeholder: 'Search...' } });
    expect(approximateAccessibleName(attrs)).toBe('Search...');
  });

  it('returns null when nothing is available', () => {
    const attrs = makeAttrs();
    expect(approximateAccessibleName(attrs)).toBe(null);
  });
});

describe('suggestLocatorsFromAria', () => {
  // Canonical case: the button text changed from "Go to page" to "Open page"
  // but the test still says getByText('Go to page').
  const renamedAria = ['- navigation', '  - button "Open page"', '- contentinfo'].join('\n');

  it('suggests a fresh same-style locator for a renamed element', () => {
    const s = suggestLocatorsFromAria({ method: 'getByText', args: ['Go to page'] }, renamedAria);
    expect(s).not.toBeNull();
    expect(s!.failing).toBe("getByText('Go to page')");
    // Same family (getByText) first, then the role-based option.
    expect(s!.suggestions[0]).toBe("getByText('Open page')");
    expect(s!.suggestions).toContain("getByRole('button', { name: 'Open page' })");
  });

  it('matches within the failed role for getByRole', () => {
    const s = suggestLocatorsFromAria({ method: 'getByRole', args: ['button', { name: 'Go to page' }] }, renamedAria);
    expect(s!.suggestions[0]).toBe("getByRole('button', { name: 'Open page' })");
  });

  it('returns null when the targeted name is still present (not a rename)', () => {
    expect(suggestLocatorsFromAria({ method: 'getByText', args: ['Open page'] }, renamedAria)).toBeNull();
  });

  it('returns null for non-name-based locators (testid / CSS)', () => {
    expect(suggestLocatorsFromAria({ method: 'getByTestId', args: ['go'] }, renamedAria)).toBeNull();
    expect(suggestLocatorsFromAria({ method: 'locator', args: ['.btn'] }, renamedAria)).toBeNull();
  });

  it('returns null without an ARIA snapshot', () => {
    expect(suggestLocatorsFromAria({ method: 'getByText', args: ['Go to page'] }, null)).toBeNull();
  });

  it('does not guess among ambiguous same-role candidates with no overlap', () => {
    const aria = ['- button "Save"', '- button "Cancel"'].join('\n');
    expect(suggestLocatorsFromAria({ method: 'getByRole', args: ['button', { name: 'Delete' }] }, aria)).toBeNull();
  });

  it('suggests getByLabel for a renamed form field', () => {
    const aria = '- textbox "Email address"';
    const s = suggestLocatorsFromAria({ method: 'getByLabel', args: ['Email'] }, aria);
    expect(s!.suggestions[0]).toBe("getByLabel('Email address')");
  });
});

describe('suggestLocatorsFromAria — heading level narrowing', () => {
  const aria = ['- heading "Overview" [level=1]', '- heading "Pricing" [level=2]', '- heading "Contact" [level=2]'].join(
    '\n',
  );

  it('a totally renamed lone h1 among h2s is suggested via its level', () => {
    const s = suggestLocatorsFromAria({ method: 'getByRole', args: ['heading', { name: 'Dashboard', level: 1 }] }, aria);
    expect(s).not.toBeNull();
    expect(s!.suggestions[0]).toBe("getByRole('heading', { name: 'Overview', level: 1 })");
  });

  it('without a level the multi-heading total rename stays ambiguous', () => {
    const s = suggestLocatorsFromAria({ method: 'getByRole', args: ['heading', { name: 'Dashboard' }] }, aria);
    expect(s).toBeNull();
  });

  it('falls back to all same-role candidates when no candidate shares the level', () => {
    const s = suggestLocatorsFromAria(
      { method: 'getByRole', args: ['heading', { name: 'Pricing plans', level: 4 }] },
      aria,
    );
    expect(s).not.toBeNull();
    expect(s!.suggestions[0]).toContain("name: 'Pricing'");
  });
});

describe('captureCallerLocation', () => {
  const frame = (file: string, line = 10) => `    at something (${file}:${line}:5)`;

  it('skips the packaged capture-fixtures proxy frame and returns the spec frame', () => {
    const stack = [
      'Error',
      frame('/pkg/node_modules/@piwitests/reporter/dist/internal/capture/locator-healing.js', 801),
      frame('/pkg/node_modules/@piwitests/reporter/dist/internal/capture/capture-fixtures.js', 457),
      frame(`${process.cwd()}/tests/heal.spec.ts`, 9),
    ].join('\n');
    expect(captureCallerLocation(stack)).toBe('tests/heal.spec.ts:9:5');
  });

  it('skips the dogfood fixtures.ts proxy frame', () => {
    const stack = [
      'Error',
      frame('/repo/reporter/dist/internal/capture/locator-healing.js', 801),
      frame(`${process.cwd()}/tests/fixtures.ts`, 200),
      frame(`${process.cwd()}/tests/checkout.spec.ts`, 42),
    ].join('\n');
    expect(captureCallerLocation(stack)).toBe('tests/checkout.spec.ts:42:5');
  });

  it("keeps a user's own fixtures file when it does not follow the capture module", () => {
    const stack = [
      'Error',
      frame('/pkg/node_modules/@piwitests/reporter/dist/internal/capture/locator-healing.js', 801),
      frame('/pkg/node_modules/@piwitests/reporter/dist/internal/capture/capture-fixtures.js', 457),
      frame(`${process.cwd()}/tests/fixtures.ts`, 88),
    ].join('\n');
    expect(captureCallerLocation(stack)).toBe('tests/fixtures.ts:88:5');
  });

  it('skips bundled dist frames by self-file identity (published package layout)', () => {
    // In the tsup bundle both this function and the proxy wrapper live in
    // dist/index.js — the module-name rules can never match, so the self-file
    // rule must consume them. The matcher frame mimics an expect() assertion.
    const stack = [
      'Error',
      frame('/pkg/node_modules/@piwitests/reporter/dist/index.js', 3163),
      frame('/pkg/node_modules/@piwitests/reporter/dist/index.js', 3100),
      frame('/pkg/node_modules/playwright/lib/matchers/matchers.js', 131),
      frame(`${process.cwd()}/tests/checkout.spec.ts`, 42),
    ].join('\n');
    expect(captureCallerLocation(stack)).toBe('tests/checkout.spec.ts:42:5');
  });

  it('skips bundle frames even when the dist import is not under node_modules', () => {
    const stack = [
      'Error',
      frame('/repo/reporter/dist/index.js', 3163),
      frame('/repo/reporter/dist/index.js', 3100),
      frame(`${process.cwd()}/tests/integration/capture.spec.ts`, 84),
    ].join('\n');
    expect(captureCallerLocation(stack)).toBe('tests/integration/capture.spec.ts:84:5');
  });

  it("keeps a user's own fixtures file directly after bundled machinery frames", () => {
    // The bundle consumed the proxy frame itself, so a fixtures-named USER
    // file coming next is a genuine call site, not the capture proxy.
    const stack = [
      'Error',
      frame('/pkg/node_modules/@piwitests/reporter/dist/index.js', 3163),
      frame('/pkg/node_modules/@piwitests/reporter/dist/index.js', 3100),
      frame(`${process.cwd()}/tests/fixtures.ts`, 88),
    ].join('\n');
    expect(captureCallerLocation(stack)).toBe('tests/fixtures.ts:88:5');
  });
});

describe('EXPECT_CAPTURE_EXPRESSIONS', () => {
  it('pins the assertion funnel method name', () => {
    expect(EXPECT_METHOD).toBe('_expect');
  });

  it('covers the common presence-proving assertions', () => {
    const presence = [
      'to.be.visible',
      'to.be.attached',
      'to.be.checked',
      'to.be.enabled',
      'to.be.focused',
      'to.have.text',
      'to.contain.text',
      'to.have.value',
      'to.have.attribute',
      'to.have.class',
      'to.have.css',
      'to.have.role',
      'to.have.accessible.name',
      'to.match.aria',
    ];
    for (const expression of presence) {
      expect(EXPECT_CAPTURE_EXPRESSIONS.has(expression), expression).toBe(true);
    }
  });

  it('excludes absence assertions — passing means the element may not exist', () => {
    for (const expression of ['to.be.hidden', 'to.be.detached']) {
      expect(EXPECT_CAPTURE_EXPRESSIONS.has(expression), expression).toBe(false);
    }
  });

  it('excludes multi-element assertions — the single-element probe would only strict-mode', () => {
    for (const expression of [
      'to.have.count',
      'to.have.text.array',
      'to.contain.text.array',
      'to.have.class.array',
      'to.have.values',
    ]) {
      expect(EXPECT_CAPTURE_EXPRESSIONS.has(expression), expression).toBe(false);
    }
  });

  it('excludes page-level assertions that run on the internal :root locator', () => {
    for (const expression of ['to.have.title', 'to.have.url']) {
      expect(EXPECT_CAPTURE_EXPRESSIONS.has(expression), expression).toBe(false);
    }
  });
});
