import { describe, test, expect } from 'vitest';
import {
  generateAlternatives as appGenerate,
  resolveAriaRole as appResolveRole,
  headingLevel as appHeadingLevel,
  classifyCssStability as appClassify,
  isAutoGenerated as appIsAuto,
  approximateAccessibleName as appApproxName,
  TAG_TO_ROLE as APP_TAG_TO_ROLE,
  INPUT_TYPE_TO_ROLE as APP_INPUT_TO_ROLE,
  CAPTURED_ATTRIBUTES as APP_CAPTURED_ATTRIBUTES,
} from '#shared/locator-generate';
import {
  generateAlternatives as repGenerate,
  resolveAriaRole as repResolveRole,
  headingLevel as repHeadingLevel,
  classifyCssStability as repClassify,
  isAutoGenerated as repIsAuto,
  approximateAccessibleName as repApproxName,
  TAG_TO_ROLE as REP_TAG_TO_ROLE,
  INPUT_TYPE_TO_ROLE as REP_INPUT_TO_ROLE,
  CAPTURED_ATTRIBUTES as REP_CAPTURED_ATTRIBUTES,
} from '../../../reporter/dist/internal/capture/locator-healing.js';
import type { ElementAttributes } from '#shared/locator-healing.types';

/**
 * The dashboard's `shared/locator-generate.ts` is a deliberate second copy of
 * the reporter's `generateAlternatives` (the reporter can't export into
 * `shared/`). These tests run BOTH implementations over the same fixtures and
 * assert identical output, so the copy can never silently drift from the
 * source. If this fails, reconcile `shared/locator-generate.ts` with
 * `reporter/src/internal/capture/locator-healing.ts`.
 */

const el = (overrides: Partial<ElementAttributes>): ElementAttributes => ({
  tagName: 'div',
  attributes: {},
  textContent: null,
  accessibleName: null,
  center: null,
  ...overrides,
});

const FIXTURES: ElementAttributes[] = [
  el({ tagName: 'button', attributes: { 'data-testid': 'submit' }, accessibleName: 'Submit', textContent: 'Submit' }),
  el({ tagName: 'button', attributes: { 'aria-label': 'Close' }, accessibleName: 'Close' }),
  el({
    tagName: 'input',
    attributes: { type: 'email', placeholder: 'Email', 'aria-label': 'Email' },
    accessibleName: 'Email',
    hasLabel: true,
  }),
  el({
    tagName: 'input',
    attributes: { type: 'text', placeholder: 'Search' },
    accessibleName: 'Search',
    hasLabel: false,
  }),
  el({ tagName: 'h1', attributes: {}, accessibleName: 'Welcome', textContent: 'Welcome' }),
  el({
    tagName: 'div',
    attributes: { role: 'heading', 'aria-level': '3' },
    accessibleName: 'Section',
    textContent: 'Section',
  }),
  el({
    tagName: 'a',
    attributes: { href: '/x', class: 'btn btn--primary hash-a1b2c3d4e5' },
    accessibleName: 'Go',
    textContent: 'Go',
  }),
  el({ tagName: 'img', attributes: { alt: 'Logo', id: 'radix-3ab' } }),
  el({
    tagName: 'span',
    attributes: { id: 'main-title', class: 'title text-lg' },
    textContent: 'Hi',
    selectorCounts: { id: 1, classes: { title: 1, 'text-lg': 4 } },
  }),
  el({
    tagName: 'button',
    attributes: { class: 'x' },
    accessibleName: 'Pay',
    textContent: 'Pay',
    rolePosition: { role: 'button', count: 1, index: 0 },
    ancestors: [
      {
        tag: 'form',
        depth: 2,
        testId: 'signup',
        id: null,
        role: null,
        ariaLabel: null,
        scopedRoleCount: 1,
        testIdCount: 1,
      },
      {
        tag: 'main',
        depth: 5,
        testId: null,
        id: 'content',
        role: 'main',
        ariaLabel: null,
        scopedRoleCount: 1,
        idCount: 1,
        roleCount: 1,
      },
    ],
  }),
  el({ tagName: 'select', attributes: { name: 'country', multiple: '' }, accessibleName: 'Country' }),
  // Ambiguity penalties, a data-* anchor, and a role-less leaf scoped by text —
  // none of the above reaches those branches.
  el({
    tagName: 'button',
    accessibleName: 'Add to cart',
    textContent: 'Add to cart',
    selectorCounts: { roleName: 2, text: 2 },
    ancestors: [
      {
        tag: 'div',
        depth: 1,
        testId: null,
        id: null,
        role: null,
        ariaLabel: null,
        scopedRoleCount: 1,
        scopedTextCount: 1,
        dataAttr: { name: 'data-product', value: '43' },
        dataAttrCount: 1,
      },
      {
        tag: 'div',
        depth: 2,
        testId: null,
        id: null,
        role: null,
        ariaLabel: null,
        scopedRoleCount: 1,
        dataAttr: { name: 'data-qa', value: 'grid' },
        dataAttrCount: 1,
      },
    ],
  }),
  el({
    tagName: 'span',
    attributes: { class: 'price' },
    textContent: '£49.99',
    selectorCounts: { text: 2, classes: { price: 4 } },
    ancestors: [
      {
        tag: 'div',
        depth: 1,
        testId: 'row-keyboard',
        id: null,
        role: null,
        ariaLabel: null,
        scopedTextCount: 1,
        testIdCount: 1,
      },
      {
        tag: 'nav',
        depth: 3,
        testId: null,
        id: 'deals',
        role: null,
        ariaLabel: null,
        scopedTextCount: 1,
        idCount: 1,
        roleCount: 1,
      },
    ],
  }),
];

describe('locator-generate drift guard (dashboard copy vs reporter source)', () => {
  test('constants match', () => {
    expect(APP_TAG_TO_ROLE).toEqual(REP_TAG_TO_ROLE);
    expect(APP_INPUT_TO_ROLE).toEqual(REP_INPUT_TO_ROLE);
    expect(APP_CAPTURED_ATTRIBUTES).toEqual(REP_CAPTURED_ATTRIBUTES);
  });

  test('generateAlternatives is identical across fixtures', () => {
    for (const fixture of FIXTURES) {
      expect(appGenerate(fixture)).toEqual(repGenerate(fixture));
    }
  });

  test('role resolution + heading level match', () => {
    for (const fixture of FIXTURES) {
      const appRole = appResolveRole(fixture);
      expect(appRole).toBe(repResolveRole(fixture));
      expect(appHeadingLevel(fixture, appRole)).toBe(repHeadingLevel(fixture, appRole));
      expect(appApproxName(fixture)).toBe(repApproxName(fixture));
    }
  });

  test('css stability + auto-generated classification match', () => {
    const classNames = ['btn', 'btn--primary', 'text-lg', 'css-1a2b3c', 'block__el', 'hash1234abcd', 'myThing', 'w-10'];
    for (const c of classNames) expect(appClassify(c)).toBe(repClassify(c));
    const ids = ['radix-3ab', 'main-title', 'ng-abc-1', ':r3:', 'item-42', 'a1b2c3d4e5f6', 'normal-id'];
    for (const id of ids) expect(appIsAuto(id)).toBe(repIsAuto(id));
  });
});
