import { describe, test, expect } from 'vitest';
import { textSimilarity, parseAriaCandidates } from '#shared/locator-fingerprint';
import {
  generateAlternatives,
  approximateAccessibleName,
  resolveAriaRole,
  headingLevel,
  classifyCssStability,
  isAutoGenerated,
  TAG_TO_ROLE,
  INPUT_TYPE_TO_ROLE,
  CAPTURED_ATTRIBUTES,
  type ElementAttributes,
} from '#shared/locator-generation';
// Imported from the reporter's *source* (vitest transpiles it), not dist/ —
// `npm run app:test:unit` must pass without a prior `npm run reporter:build`.
import {
  nameSimilarity,
  parseAriaRoleName,
  generateAlternatives as reporterGenerateAlternatives,
  approximateAccessibleName as reporterApproximateAccessibleName,
  resolveAriaRole as reporterResolveAriaRole,
  headingLevel as reporterHeadingLevel,
  classifyCssStability as reporterClassifyCssStability,
  isAutoGenerated as reporterIsAutoGenerated,
  TAG_TO_ROLE as REPORTER_TAG_TO_ROLE,
  INPUT_TYPE_TO_ROLE as REPORTER_INPUT_TYPE_TO_ROLE,
  CAPTURED_ATTRIBUTES as REPORTER_CAPTURED_ATTRIBUTES,
} from '../../../reporter/src/internal/capture/locator-healing';

/**
 * Drift guard: the reporter package publishes standalone to npm and cannot
 * import application/shared, so it hand-mirrors pure helpers. These tests
 * feed both implementations the same fixtures and require identical output —
 * silent drift (which has bitten this pairing before) becomes a red test.
 */

describe('reporter ↔ shared drift guard', () => {
  const SIMILARITY_FIXTURES: Array<[string | null, string | null]> = [
    ['Go to page', 'Open page'],
    ['Submit order', 'Submit order'],
    ['Submit', 'Cancel'],
    ['', ''],
    [null, 'Delete'],
    ['Delete', null],
    ['  Mixed-CASE, punctuation!  ', 'mixed case punctuation'],
    ['one two three', 'three two one'],
    ['a1 b2', 'a1 c3'],
  ];

  test('nameSimilarity (reporter) matches textSimilarity (shared) on all fixtures', () => {
    for (const [a, b] of SIMILARITY_FIXTURES) {
      expect(nameSimilarity(a, b), `similarity("${a}", "${b}")`).toBe(textSimilarity(a, b));
    }
  });

  const ARIA_FIXTURES = [
    '- button "Open page"\n- heading "Welcome" [level=1]\n- textbox "Email"\n- generic',
    '- list\n  - listitem "First"\n  - listitem "Second"',
    '- group\n- paragraph\n- link "Docs \\"quoted\\""',
    '',
    '- button\n- checkbox "Remember me" [checked]',
    // Heading levels — with ref markers, nameless headings, and bracket text
    // inside the quoted name that must NOT be read as a level.
    '- heading "Overview" [level=2] [ref=e7]\n- heading [level=3]\n- heading "Read [level=9] docs" [level=1]',
  ];

  test('parseAriaRoleName (reporter) matches parseAriaCandidates (shared) on all fixtures', () => {
    for (const snapshot of ARIA_FIXTURES) {
      expect(parseAriaRoleName(snapshot), `parse(${JSON.stringify(snapshot)})`).toEqual(parseAriaCandidates(snapshot));
    }
  });

  // ── Alternative generator (shared/locator-generation ↔ reporter) ──────────
  // The dashboard's snapshot picker generates alternatives in the browser from
  // `shared/locator-generation.ts`, a mirror of the reporter's generator. A
  // score-tier or gating change in one copy must fail here, not diverge silently.

  const ELEMENT_FIXTURES: ElementAttributes[] = [
    // Unique testid + role + name + mixed-stability classes
    {
      tagName: 'button',
      attributes: { 'data-testid': 'pay-btn', class: 'btn btn-primary' },
      textContent: 'Pay now',
      accessibleName: 'Pay now',
      center: { x: 10, y: 20 },
      hasLabel: false,
      selectorCounts: { testId: 1, classes: { btn: 5, 'btn-primary': 1 } },
    },
    // Labeled email input (getByLabel gate open)
    {
      tagName: 'input',
      attributes: { type: 'email', placeholder: 'you@example.com', name: 'email' },
      textContent: null,
      accessibleName: 'Email address',
      center: null,
      hasLabel: true,
      selectorCounts: { name: 1 },
    },
    // Placeholder-named input without a real label (getByLabel gate closed)
    {
      tagName: 'input',
      attributes: { placeholder: 'Search' },
      textContent: null,
      accessibleName: 'Search',
      center: null,
      hasLabel: false,
    },
    // Heading with a tag-derived level
    { tagName: 'h2', attributes: {}, textContent: 'Overview', accessibleName: 'Overview', center: null },
    // Heading via explicit role + aria-level
    {
      tagName: 'div',
      attributes: { role: 'heading', 'aria-level': '3' },
      textContent: 'Sub',
      accessibleName: 'Sub',
      center: null,
    },
    // Ambiguous testid + auto-generated id + title fallback
    {
      tagName: 'a',
      attributes: { 'data-testid': 'row-link', id: 'radix-:r3:', href: '/x', title: 'Open row' },
      textContent: 'Open',
      accessibleName: 'Open',
      center: null,
      selectorCounts: { testId: 4, id: 1 },
    },
    // Structural context: anchor-worthy ancestors + role position, no own hooks
    {
      tagName: 'button',
      attributes: {},
      textContent: 'Delete',
      accessibleName: 'Delete',
      center: null,
      rolePosition: { role: 'button', count: 3, index: 1 },
      ancestors: [
        {
          tag: 'div',
          depth: 1,
          testId: 'cart-row',
          id: null,
          role: null,
          ariaLabel: null,
          scopedRoleCount: 1,
          testIdCount: 1,
        },
        {
          tag: 'section',
          depth: 2,
          testId: null,
          id: 'summary',
          role: null,
          ariaLabel: null,
          scopedRoleCount: 1,
          idCount: 1,
        },
        { tag: 'nav', depth: 3, testId: null, id: null, role: null, ariaLabel: null, scopedRoleCount: 1, roleCount: 1 },
      ],
    },
    // Multi-select with an aria-label that differs from the accessible name
    {
      tagName: 'select',
      attributes: { multiple: '', 'aria-label': 'Pick fruits' },
      textContent: null,
      accessibleName: 'Fruits',
      center: null,
    },
  ];

  test('generateAlternatives (reporter) matches shared on all fixtures', () => {
    for (const fx of ELEMENT_FIXTURES) {
      expect(reporterGenerateAlternatives(fx), `generateAlternatives(<${fx.tagName}>)`).toEqual(
        generateAlternatives(fx),
      );
    }
  });

  test('role/name helpers (reporter) match shared on all fixtures', () => {
    for (const fx of ELEMENT_FIXTURES) {
      const role = resolveAriaRole(fx);
      expect(reporterResolveAriaRole(fx), `resolveAriaRole(<${fx.tagName}>)`).toBe(role);
      expect(reporterHeadingLevel(fx, role), `headingLevel(<${fx.tagName}>)`).toBe(headingLevel(fx, role));
      expect(reporterApproximateAccessibleName(fx), `approximateAccessibleName(<${fx.tagName}>)`).toBe(
        approximateAccessibleName(fx),
      );
    }
  });

  const CLASS_FIXTURES = [
    'submit-button',
    'bg-red-500',
    'css-1a2b3c',
    'sc-fzXfPi',
    'block__element',
    'my_class',
    'btnPrimary',
    'a1b2c3d4e5',
    'flex',
    'card--active',
  ];

  test('classifyCssStability (reporter) matches shared on all fixtures', () => {
    for (const cls of CLASS_FIXTURES) {
      expect(reporterClassifyCssStability(cls), `classifyCssStability("${cls}")`).toBe(classifyCssStability(cls));
    }
  });

  const AUTOGEN_FIXTURES = [
    '550e8400-e29b-41d4-a716-446655440000',
    'deadbeef01',
    'input-42',
    'ng-pristine',
    'radix-:r1:',
    ':r5:',
    '«r7»',
    'submit-button',
    'emotion-0',
    'mui-typography',
  ];

  test('isAutoGenerated (reporter) matches shared on all fixtures', () => {
    for (const value of AUTOGEN_FIXTURES) {
      expect(reporterIsAutoGenerated(value), `isAutoGenerated("${value}")`).toBe(isAutoGenerated(value));
    }
  });

  test('role maps and captured-attribute whitelist are identical', () => {
    expect(REPORTER_TAG_TO_ROLE).toEqual(TAG_TO_ROLE);
    expect(REPORTER_INPUT_TYPE_TO_ROLE).toEqual(INPUT_TYPE_TO_ROLE);
    expect(REPORTER_CAPTURED_ATTRIBUTES).toEqual(CAPTURED_ATTRIBUTES);
  });
});
